### ISSUE TITLE
cheatsheet does not render images on MacOS

### ISSUE THREAD

**Issue by wsargent** [asciidocfx/AsciidocFX#137]
When the Asciidoc Cheatsheet menu item is selected from the sidebar, then the document created (cheatsheet.adoc) results in the following exception

```
ERROR => Problem occured while generating MathJax png
java.nio.file.AccessDeniedException: /Applications/AsciidocFX.app/Contents/java/app/conf/cheatsheet/tex-formula.png
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[na:1.8.0_60-ea]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_60-ea]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_60-ea]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[na:1.8.0_60-ea]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[na:1.8.0_60-ea]
	at java.nio.file.Files.newOutputStream(Files.java:216) ~[na:1.8.0_60-ea]
	at java.nio.file.Files.write(Files.java:3292) ~[na:1.8.0_60-ea]
	at com.kodcu.service.extension.MathJaxService.saveAsPng(MathJaxService.java:122) [AsciidocFX-1.3.7.jar:1.3.7]
	at com.kodcu.service.extension.MathJaxService.svgToPng(MathJaxService.java:75) [AsciidocFX-1.3.7.jar:1.3.7]
	at com.kodcu.controller.ApplicationController.lambda$svgToPng$22(ApplicationController.java:479) [AsciidocFX-1.3.7.jar:1.3.7]
	at com.kodcu.service.ThreadService$1.call(ThreadService.java:35) ~[AsciidocFX-1.3.7.jar:1.3.7]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60-ea]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_60-ea]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60-ea]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60-ea]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60-ea]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60-ea]
```

The files are owned by root and are world readable, but only root can write to them.  I think the problem may be that the images are opened "writable" and so cannot be accessed by the JVM on those terms.

**Comment by rahmanusta** [comment]
@wsargent It is because the installdir of AsciidocFX is not writeable. You can save as cheatsheet to a writable directory. But, we need to move write needed contents of AsciidocFX to a writable directory by default.

**Comment by rahmanusta** [comment]
@wsargent Could you try v1.3.9 ?

**Comment by wsargent** [comment]
Works fine in 1.3.9.
