### ISSUE TITLE
HTML: Base64 encoding of PNG images.

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#142]
Hi @rahmanusta 

Enjoying using the latest release. Thanks for all the hard work!

This is a new feature request. I sometimes email AsciidocFX generated HTML files to others to review. The HTML file needs to be self-contained and not have references to other local files such as images. To workaround current limitations, the following Python script is used to Base64 encode the PNG images referenced by the HTML file that AsciidocFX created, and thereby creating a new self-contained HTML file.

```
import sys
import base64

lines = open(sys.argv[1], "r+").readlines()

# Translate
#   <img src="diagram.png" alt="diagram.png">
# to
#   <img src="data:image/png;base64,ENCODED_PNG" alt="diagram.png">

for line in lines:
    line = line[:-1]
    if line[:9] == "<img src=":
        # ['<img src=', 'diagram.png', ' alt=', 'diagram.png', '>']
        tokens = line.split('"')
        filename = tokens[1]
        encoded = base64.b64encode(open(filename, "rb").read())
        s = tokens[0] + '"data:image/png;base64,' + encoded + '"' + tokens[2] + '"' + tokens[3] + '"'  + tokens[4]
        print s
    else:
        print line
```

Please consider adding an HTML export option to AsciidocFX that instead of linking to images:
```
<img src="diagram.png" alt="diagram.png">
```
will Base64 encode images:

```
<img src="data:image/png;base64,ENCODED_PNG" alt="diagram.png">
```

where ENCODED_PNG is the Base64 string encoding of the PNG image. Support for all images types supported by AsciidocFX should be provided, not just PNG.

**Comment by rahmanusta** [comment]
Hi @wfouche ;

Could you try Clone Html menu item under HTML menu. This feature is already implemented if there is no bug or misconception

**Comment by wfouche** [comment]
Hi @rahmanusta 

```
        htmlProMenu.getItems().add(MenuItemBuilt.item("Save").click(event -> {
            this.generateHtml();
        }));
        htmlProMenu.getItems().add(MenuItemBuilt.item("Save as").click(event -> {
            this.generateHtml(true);
        }));
        htmlProMenu.getItems().add(MenuItemBuilt.item("Copy source").tip("Copy HTML source").click(event -> {
            this.cutCopy(lastRendered.getValue());
        }));
        htmlProMenu.getItems().add(MenuItemBuilt.item("Clone source").tip("Copy HTML source (Embedded images)").click(event -> {
            htmlPane.call("imageToBase64Url", new Object[]{});
        }));
```

What is being requested is an additional menu option called Export (which is similar to Save) that willl save document.adoc as document.html but Base64 encode all images. 

```
        htmlProMenu.getItems().add(MenuItemBuilt.item("Export").click(event -> {
            this.generateHtml(false,true);
        }));

```
This would require generateHtml to be defined as:

```
private void generateHtml(boolean askPath, boolean base64Urls) {
```

I don't understand what "Clone source" actually does, but it does not seem to create a new HTML file on disk as "Save" or "Save as" does.

**Comment by rahmanusta** [comment]
@wfouche Clone Html copies HTML content with base64 images to clipboard

**Comment by wfouche** [comment]
@rahmanusta I'll try the clipboard approach.

The :data-uri: attribute that Asciidoctor supports is a better option to explore.

* http://asciidoctor.org/docs/render-documents/

I tried using :data-uri: with AsciidocFX but it then cannot generate HTML. The HTML "Save" option fails.

````
ERROR => Problem occured while converting to HTML
java.util.concurrent.CompletionException: netscape.javascript.JSException: TypeError: undefined is not a function (evaluating 'A.$exception("asciidoctor: FAILED: "+((f=q["$[]"]("docfile"))!==!1&&f!==e?f:"<stdin>")+": Failed to parse AsciiDoc source, "+A.$message())')

	at java.util.concurrent.CompletableFuture.reportJoin(Unknown Source) ~[na:1.8.0_60]

	at java.util.concurrent.CompletableFuture.join(Unknown Source) ~[na:1.8.0_60]

	at com.kodcu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:131) ~[AsciidocFX-1.3.7.jar:1.3.7]

	at com.kodcu.engine.AsciidocWebkitConverter.convertHtml(AsciidocWebkitConverter.java:158) ~[AsciidocFX-1.3.7.jar:1.3.7]

	at com.kodcu.service.convert.html.HtmlBookConverter.convert(HtmlBookConverter.java:68) ~[AsciidocFX-1.3.7.jar:1.3.7]

	at com.kodcu.controller.ApplicationController.lambda$generateHtml$16(ApplicationController.java:496) [AsciidocFX-1.3.7.jar:1.3.7]

	at com.kodcu.service.ThreadService$1.call(ThreadService.java:35) ~[AsciidocFX-1.3.7.jar:1.3.7]

	at javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[jfxrt.jar:na]

	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_60]

	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_60]

	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_60]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_60]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_60]

	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_60]

Caused by: netscape.javascript.JSException: TypeError: undefined is not a function (evaluating 'A.$exception("asciidoctor: FAILED: "+((f=q["$[]"]("docfile"))!==!1&&f!==e?f:"<stdin>")+": Failed to parse AsciiDoc source, "+A.$message())')

	at com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source) ~[jfxrt.jar:na]

	at com.sun.webkit.WebPage.twkExecuteScript(Native Method) ~[jfxrt.jar:na]

	at com.sun.webkit.WebPage.executeScript(Unknown Source) ~[jfxrt.jar:na]

	at javafx.scene.web.WebEngine.executeScript(Unknown Source) ~[jfxrt.jar:na]

	at com.kodcu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:136) ~[AsciidocFX-1.3.7.jar:1.3.7]

	at com.kodcu.engine.AsciidocWebkitConverter.lambda$null$177(AsciidocWebkitConverter.java:123) ~[AsciidocFX-1.3.7.jar:1.3.7]

	at com.sun.javafx.application.PlatformImpl.lambda$null$174(Unknown Source) ~[jfxrt.jar:na]

	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_60]

	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(Unknown Source) ~[jfxrt.jar:na]

	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[jfxrt.jar:na]

	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:na]

	at com.sun.glass.ui.win.WinApplication.lambda$null$149(Unknown Source) ~[jfxrt.jar:na]

	... 1 common frames omitted



````

**Comment by wfouche** [comment]
Closing this issue and opening a new one related to attribute :data-uri:
