### ISSUE TITLE
Writing Docbook errors with cvc-complex-type.2.4.a: Invalid content was found starting with element 'emphasis'

### ISSUE THREAD

**Issue by jafin** [asciidocfx/AsciidocFX#156]
Unsure if I am writing invalid asciidoc, but this line

```
Where `_{key}_` denotes the apikey defined in the web.cofig value `*security:HealthCheckApiKey*`
```

Generates this exception in asciidocFX 1.3.9 when exporting to Docbook.  It appears fine in HTML output.

```
ERROR => Please fix Docbook validation error. LineNumber: 9, Column: 35
org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'emphasis'. One of '{"http://docbook.org/ns/docbook":inlinemediaobject, "http://docbook.org/ns/docbook":remark, "http://docbook.org/ns/docbook":superscript, "http://docbook.org/ns/docbook":subscript, "http://docbook.org/ns/docbook":xref, "http://docbook.org/ns/docbook":link, "http://docbook.org/ns/docbook":olink, "http://docbook.org/ns/docbook":anchor, "http://docbook.org/ns/docbook":biblioref, "http://docbook.org/ns/docbook":alt, "http://docbook.org/ns/docbook":annotation, "http://docbook.org/ns/docbook":indexterm, "http://docbook.org/ns/docbook":phrase, "http://docbook.org/ns/docbook":replaceable}' is expected.

    at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.impl.xs.XMLSchemaValidator.reportSchemaError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.jaxp.validation.StreamValidatorHelper.validate(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
    at javax.xml.validation.Validator.validate(Unknown Source) ~[na:1.8.0_60]
    at com.kodcu.service.convert.docbook.DocbookValidator.validateDocbook(DocbookValidator.java:53) ~[AsciidocFX-1.3.9.jar:1.3.9]
    at com.kodcu.service.convert.docbook.DocBookConverter.convert(DocBookConverter.java:54) [AsciidocFX-1.3.9.jar:1.3.9]
    at com.kodcu.controller.ApplicationController.lambda$convertDocbook$8(ApplicationController.java:416) [AsciidocFX-1.3.9.jar:1.3.9]
    at com.kodcu.service.ThreadService$1.call(ThreadService.java:36) ~[AsciidocFX-1.3.9.jar:1.3.9]
    at javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[jfxrt.jar:na]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_60]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_60]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_60]
    at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_60]
```

**Comment by ozlerhakan** [comment]
Hi @jafin ,

This is a valid asciidoc format but isn't valid for DocBook. This issue is related to [#127](https://github.com/asciidocfx/AsciidocFX/issues/127). The current docbook in AFX does not allow you to add bold and italic styles into a monospace format. To fix that issue we have created a branch called [fix-127](https://github.com/asciidocfx/AsciidocFX/tree/fix-127). Probably It will be merged in upcoming days.
