### ISSUE TITLE
Arch Linux Java Error

### ISSUE THREAD

**Issue by nobicycle** [asciidocfx/AsciidocFX#159]
Hi,
Thanks for the app.

From within the extracted archive (version without JRE)
$archlinux-java get
java-8-openjdk/jre

$./AsciidocFX
java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:59)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

**Comment by rahmanusta** [comment]
@nobicycle It seems JRE 8 is not installed with javafx, could you try jre bundled version of AsciidocFX to be sure?

**Comment by nobicycle** [comment]
Hi Rahmanusta
As mentioned above, my Arch system reports JRE 8 is available.
$archlinux-java get
java-8-openjdk/jre
Of course I could use the JRE bundled version, but I isn't Java supposed to be "run everywhere"? :-)
Thanks for the app.

**Comment by rahmanusta** [comment]
@nobicycle Try to run any javafx app, you will see tha truth :) Or you can install oracle jdk, or follow a tutorial to install javafx with openjdk, or use jre bundled version :)
