### ISSUE TITLE
ERROR => Problem occured while converting to PDF

### ISSUE THREAD

**Issue by gmind7** [asciidocfx/AsciidocFX#166]
os : windows7

asciidoctor syntax error
= mainTtile: subTitle

ERROR => Problem occured while converting to PDF
java.util.concurrent.CompletionException: netscape.javascript.JSException: TypeError: undefined is not a function (evaluating 'b.$rpartition(k)')

	at java.util.concurrent.CompletableFuture.reportJoin(Unknown Source) ~[na:1.8.0_66]

	at java.util.concurrent.CompletableFuture.join(Unknown Source) ~[na:1.8.0_66]

	at com.kodcu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:161) ~[AsciidocFX-1.4.0.jar:1.4.0]

	at com.kodcu.engine.AsciidocWebkitConverter.convertDocbook(AsciidocWebkitConverter.java:178) ~[AsciidocFX-1.4.0.jar:1.4.0]

	at com.kodcu.service.convert.docbook.DocBookConverter.convert(DocBookConverter.java:52) ~[AsciidocFX-1.4.0.jar:1.4.0]

	at com.kodcu.service.convert.pdf.PdfBookConverter.convert(PdfBookConverter.java:83) ~[AsciidocFX-1.4.0.jar:1.4.0]

	at com.kodcu.controller.ApplicationController.lambda$generatePdf$2(ApplicationController.java:375) [AsciidocFX-1.4.0.jar:1.4.0]

	at com.kodcu.service.ThreadService$1.call(ThreadService.java:39) ~[AsciidocFX-1.4.0.jar:1.4.0]

	at javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[jfxrt.jar:na]

	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_66]

	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_66]

	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_66]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[na:1.8.0_66]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:1.8.0_66]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_66]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_66]

	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_66]

Caused by: netscape.javascript.JSException: TypeError: undefined is not a function (evaluating 'b.$rpartition(k)')

	at com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source) ~[jfxrt.jar:na]

	at com.sun.webkit.WebPage.twkExecuteScript(Native Method) ~[jfxrt.jar:na]

	at com.sun.webkit.WebPage.executeScript(Unknown Source) ~[jfxrt.jar:na]

	at javafx.scene.web.WebEngine.executeScript(Unknown Source) ~[jfxrt.jar:na]

	at com.kodcu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:166) ~[AsciidocFX-1.4.0.jar:1.4.0]

	at com.kodcu.engine.AsciidocWebkitConverter.lambda$null$188(AsciidocWebkitConverter.java:153) ~[AsciidocFX-1.4.0.jar:1.4.0]

	at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Source) ~[jfxrt.jar:na]

	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]

	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown Source) ~[jfxrt.jar:na]

	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[jfxrt.jar:na]

	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:na]

	at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source) ~[jfxrt.jar:na]

	... 1 common frames omitted

**Comment by rahmanusta** [comment]
@gmind7 Could you share your asciidoc document to test it?

**Comment by gmind7** [comment]
ok. print screen
----------------------------
= mainTitle AsciidoctorFX: subTitle

== chapter 1.

testtesttesttestd
----------------------------
![asciidoctor-subtitle-error](https://cloud.githubusercontent.com/assets/4793831/11085355/a63e6b3a-8888-11e5-9c9d-91feeb77335a.jpg)

**Comment by rahmanusta** [comment]
@gmind7 It is a bug. I remember we fixed it before, but we are seeing issue again. The problem caused from ":" character in title.

**Comment by rahmanusta** [comment]
@gmind7 could you please try v1.4.1 ? it seems fixed now.
