### ISSUE TITLE
Temporary xml version of the asciidoc is opened in a new tab and no PDF produced

### ISSUE THREAD

**Issue by DanielGrigoras** [asciidocfx/AsciidocFX#174]
Hi,

For some reason, since yesterday, even before updating from 1.4.1 to 1.4.2, the PDF version is no longer produced and instead, the temporary xml version of the asciidoc is opened in a new tab (see screenshot bellow).

![xml version displayed and no pdf produced](https://cloud.githubusercontent.com/assets/15011993/11594065/a19ce41e-9ab0-11e5-83f4-b92b53990864.png)

**Comment by rahmanusta** [comment]
Hi @DanielGrigoras , you are seeing it because there is a docbook syntax error, you can look at log output and see which line has an error, and fix it in asciidoc side. If you send me your adoc I can fix it also.

**Comment by DanielGrigoras** [comment]
This happens with any of the documents, including the syntax error-free one I've sent you earlier on thread #172 about "TOC printed in appendix B without specifying this".

**Comment by rahmanusta** [comment]
@DanielGrigoras I tried your document zipped before, and I see no error. Could you send me showed docbook and error line number ?

**Comment by DanielGrigoras** [comment]
Well, I have just installed version 1.4.3 and I have not re-encountered the above said PDF production error.

**Comment by rahmanusta** [comment]
Good sir :+1: , Thanks.

**Comment by DanielGrigoras** [comment]
Well, I have just re-encountered this error after I opened another asciidoc and tried producing its PDF version.
Here's the error message I get:
```
ERROR => Please fix Docbook validation error. LineNumber: 433, Column: 41
org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'appendix'. One of '{"http://docbook.org/ns/docbook":section, "http://docbook.org/ns/docbook":simplesect, "http://docbook.org/ns/docbook":glossary, "http://docbook.org/ns/docbook":bibliography, "http://docbook.org/ns/docbook":index, "http://docbook.org/ns/docbook":toc}' is expected.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.impl.xs.XMLSchemaValidator.reportSchemaError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.jaxp.validation.StreamValidatorHelper.validate(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
	at javax.xml.validation.Validator.validate(Unknown Source) ~[na:1.8.0_66]
	at com.kodcu.service.convert.docbook.DocbookValidator.validateDocbook(DocbookValidator.java:63) ~[AsciidocFX-1.4.3.jar:1.4.3]
	at com.kodcu.service.convert.docbook.DocBookConverter.convert(DocBookConverter.java:54) [AsciidocFX-1.4.3.jar:1.4.3]
	at com.kodcu.service.convert.pdf.PdfBookConverter.convert(PdfBookConverter.java:83) [AsciidocFX-1.4.3.jar:1.4.3]
	at com.kodcu.controller.ApplicationController.lambda$generatePdf$2(ApplicationController.java:390) [AsciidocFX-1.4.3.jar:1.4.3]
	at com.kodcu.service.ThreadService$1.call(ThreadService.java:35) ~[AsciidocFX-1.4.3.jar:1.4.3]
	at javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_66]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_66]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_66]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_66]
```

Here's what written in asciidoc:
```
[appendix]
SD card limitations
-------------------
```

And here's how that's translated in the xml version:
```
433: <appendix xml:id="_sd_card_limitations">
434: <title>SD card limitations</title>"
```

**Comment by rahmanusta** [comment]
You asciidoc document has syntax error @DanielGrigoras ;

Options: 

* You can close Docbook validation in Settings page
* You can fix syntax error by following line
* Or you can send your document and I can fix the syntax issue

**Comment by DanielGrigoras** [comment]
Well, the documents I work with contain corporately confidential information, so I cannot send them to you.
I did look up the line that was said to have a syntax error, but everything looked fine, which is why I've sent you the sample codes above, thinking that you would be able to spot the error that AsciidocFX purported to exist there.

**Comment by rahmanusta** [comment]
Maybe you can send me a snippet of example that causes to this issue with lorem ipsum dolar sit amet

**Comment by DanielGrigoras** [comment]
I did. The documents are/should be the same.

**Comment by srlopez** [comment]
I have the same issue, just a temporary xml but no pdf output.
Looking for a error in xml , and nothing appear.

I am working in linux with the last version of AsciidocFX.
¿How can i workaround with this issue?
Thanks @rahmanusta . Great work

**Comment by rahmanusta** [comment]
Hi @srlopez , it means produced Docbook is not valid and red marks says the problem in the opened xml output. You should see which part of Asciidoc document causes invalid Docbook output. Another choice may be, you can disable Docbook validation in Settings panel. If you can't solve the issue, you can send me the document to find problem.

Thanks

**Comment by srlopez** [comment]
Thanks again @rahmanusta .
I did not see a red square within a X in a line in the xml file.
That was the error.

**Comment by rahmanusta** [comment]
@srlopez Do you see an error output in log console like below;?

`ERROR => Please fix Docbook validation error. LineNumber: 433, Column: 41`

Thanks.

**Comment by srlopez** [comment]
No.
I just see an 'x' on the XML file opened by AsciidocFx.

I just removed that line on the original adoc file. But I don't kown what's
wrong on this line ( it,s a remark in a work in progress)

=== see file question 1 d .doc

Maybe understand that include that file?

But don't worry by this.
Thaks friend
