### ISSUE TITLE
The element type "keycap" must be terminated by the matching end-tag "</keycap>".

### ISSUE THREAD

**Issue by Lionia** [asciidocfx/AsciidocFX#194]
Using version 1.4.0 this does not work:

|kbd:[icon:arrow-down[]] |Flytter fokus nedover i listen over registrerte koder og åpner denne for redigering.

This will result in following error when attempting to save as pdf:

ERROR => Please fix Docbook validation error. LineNumber: 434, Column: 23
org.xml.sax.SAXParseException: The element type "keycap" must be terminated by the matching end-tag "</keycap>".

	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) ~[xercesImpl-2.9.1.jar:na]

	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]

	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]

	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]

	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]

	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source) ~[xercesImpl-2.9.1.jar:na]

	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source) ~[xercesImpl-2.9.1.jar:na]

	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.9.1.jar:na]

	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.9.1.jar:na]

	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.9.1.jar:na]

	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.9.1.jar:na]

	at org.apache.xerces.jaxp.validation.StreamValidatorHelper.validate(Unknown Source) ~[xercesImpl-2.9.1.jar:na]

	at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source) ~[xercesImpl-2.9.1.jar:na]

	at javax.xml.validation.Validator.validate(Unknown Source) ~[na:1.8.0_66]

	at com.kodcu.service.convert.docbook.DocbookValidator.validateDocbook(DocbookValidator.java:53) ~[AsciidocFX-1.4.0.jar:1.4.0]

	at com.kodcu.service.convert.docbook.DocBookConverter.convert(DocBookConverter.java:54) [AsciidocFX-1.4.0.jar:1.4.0]

	at com.kodcu.service.convert.pdf.PdfBookConverter.convert(PdfBookConverter.java:83) [AsciidocFX-1.4.0.jar:1.4.0]

	at com.kodcu.controller.ApplicationController.lambda$generatePdf$2(ApplicationController.java:375) [AsciidocFX-1.4.0.jar:1.4.0]

	at com.kodcu.service.ThreadService$1.call(ThreadService.java:39) ~[AsciidocFX-1.4.0.jar:1.4.0]

	at javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[jfxrt.jar:na]

	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_66]

	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_66]

	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_66]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[na:1.8.0_66]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:1.8.0_66]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_66]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_66]

	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_66]

**Comment by rahmanusta** [comment]
Latest version is v1.4.5 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.5. Did you try it ?
