### ISSUE TITLE
Save to PDF fails with repeated "Unsupported TrueType font: No Unicode or Symbol cmap..."

### ISSUE THREAD

**Issue by mmatti** [asciidocfx/AsciidocFX#200]
Fresh install of AFX on Mac running El Capitan 10.11.2. Preview pane looks OK, preview in browser looks OK, but attempting to save a PDF results in an orphaned asciidoc-temp####.xml file and this in the log:

```
DEBUG => Watchservice started for: /Users/Michael/Documents/Cloud/Dropbox/sapiens/Titanium/documentation/Interactions

DEBUG => Filesystem Tree relisted for /Users/Michael/Documents/Cloud/Dropbox/sapiens/Titanium/documentation/Interactions

ERROR => null
java.lang.IllegalArgumentException: null
	at java.nio.Buffer.position(Buffer.java:244) ~[na:1.8.0_66]
	at sun.nio.cs.UTF_8.updatePositions(UTF_8.java:77) ~[na:1.8.0_66]
	at sun.nio.cs.UTF_8.access$200(UTF_8.java:57) ~[na:1.8.0_66]
	at sun.nio.cs.UTF_8$Decoder.xflow(UTF_8.java:208) ~[na:1.8.0_66]
	at sun.nio.cs.UTF_8$Decoder.decodeArrayLoop(UTF_8.java:319) ~[na:1.8.0_66]
	at sun.nio.cs.UTF_8$Decoder.decodeLoop(UTF_8.java:412) ~[na:1.8.0_66]
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:579) ~[na:1.8.0_66]
	at morfologik.speller.Speller.findRepl(Speller.java:464) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:526) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:526) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:471) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findReplacements(Speller.java:434) ~[morfologik-speller-1.10.0.jar:na]
	at com.kodcu.spell.dictionary.LanguageSpeller.findSuggestions(LanguageSpeller.java:70) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.spell.dictionary.DictionaryService.lambda$processTokens$309(DictionaryService.java:76) [AsciidocFX-1.4.5.jar:1.4.5]
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_66]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[na:1.8.0_66]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_66]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_66]
	at com.kodcu.spell.dictionary.DictionaryService.processTokens(DictionaryService.java:80) [AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.controller.ApplicationController.lambda$processTokens$147(ApplicationController.java:2067) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.service.ThreadService$1.call(ThreadService.java:39) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]


ERROR => null
java.lang.IllegalArgumentException: null
	at java.nio.Buffer.position(Buffer.java:244) ~[na:1.8.0_66]
	at sun.nio.cs.UTF_8$Decoder.malformed(UTF_8.java:171) ~[na:1.8.0_66]
	at sun.nio.cs.UTF_8$Decoder.decodeArrayLoop(UTF_8.java:317) ~[na:1.8.0_66]
	at sun.nio.cs.UTF_8$Decoder.decodeLoop(UTF_8.java:412) ~[na:1.8.0_66]
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:579) ~[na:1.8.0_66]
	at morfologik.speller.Speller.findRepl(Speller.java:464) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:526) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:526) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findReplacements(Speller.java:434) ~[morfologik-speller-1.10.0.jar:na]
	at com.kodcu.spell.dictionary.LanguageSpeller.findSuggestions(LanguageSpeller.java:70) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.spell.dictionary.DictionaryService.lambda$processTokens$309(DictionaryService.java:76) [AsciidocFX-1.4.5.jar:1.4.5]
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_66]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[na:1.8.0_66]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_66]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_66]
	at com.kodcu.spell.dictionary.DictionaryService.processTokens(DictionaryService.java:80) [AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.controller.ApplicationController.lambda$processTokens$147(ApplicationController.java:2067) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.service.ThreadService$1.call(ThreadService.java:39) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]


ERROR => null
java.lang.IllegalArgumentException: null
	at java.nio.Buffer.position(Buffer.java:244) ~[na:1.8.0_66]
	at sun.nio.cs.UTF_8.updatePositions(UTF_8.java:77) ~[na:1.8.0_66]
	at sun.nio.cs.UTF_8.access$200(UTF_8.java:57) ~[na:1.8.0_66]
	at sun.nio.cs.UTF_8$Decoder.malformed(UTF_8.java:173) ~[na:1.8.0_66]
	at sun.nio.cs.UTF_8$Decoder.decodeArrayLoop(UTF_8.java:317) ~[na:1.8.0_66]
	at sun.nio.cs.UTF_8$Decoder.decodeLoop(UTF_8.java:412) ~[na:1.8.0_66]
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:579) ~[na:1.8.0_66]
	at morfologik.speller.Speller.findRepl(Speller.java:464) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:471) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:471) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:526) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findReplacements(Speller.java:434) ~[morfologik-speller-1.10.0.jar:na]
	at com.kodcu.spell.dictionary.LanguageSpeller.findSuggestions(LanguageSpeller.java:70) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.spell.dictionary.DictionaryService.lambda$processTokens$309(DictionaryService.java:76) [AsciidocFX-1.4.5.jar:1.4.5]
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_66]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[na:1.8.0_66]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_66]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_66]
	at com.kodcu.spell.dictionary.DictionaryService.processTokens(DictionaryService.java:80) [AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.controller.ApplicationController.lambda$processTokens$147(ApplicationController.java:2067) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.service.ThreadService$1.call(ThreadService.java:39) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]


ERROR => null
java.nio.BufferUnderflowException: null
	at java.nio.Buffer.nextGetIndex(Buffer.java:500) ~[na:1.8.0_66]
	at java.nio.HeapCharBuffer.get(HeapCharBuffer.java:135) ~[na:1.8.0_66]
	at morfologik.speller.Speller.findRepl(Speller.java:476) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:471) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:526) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:526) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findReplacements(Speller.java:434) ~[morfologik-speller-1.10.0.jar:na]
	at com.kodcu.spell.dictionary.LanguageSpeller.findSuggestions(LanguageSpeller.java:70) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.spell.dictionary.DictionaryService.lambda$processTokens$309(DictionaryService.java:76) [AsciidocFX-1.4.5.jar:1.4.5]
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_66]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[na:1.8.0_66]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_66]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_66]
	at com.kodcu.spell.dictionary.DictionaryService.processTokens(DictionaryService.java:80) [AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.controller.ApplicationController.lambda$processTokens$147(ApplicationController.java:2067) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.service.ThreadService$1.call(ThreadService.java:39) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]


ERROR => null
java.nio.BufferUnderflowException: null
	at java.nio.Buffer.nextGetIndex(Buffer.java:500) ~[na:1.8.0_66]
	at java.nio.HeapCharBuffer.get(HeapCharBuffer.java:135) ~[na:1.8.0_66]
	at morfologik.speller.Speller.findRepl(Speller.java:476) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:471) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:526) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findRepl(Speller.java:526) ~[morfologik-speller-1.10.0.jar:na]
	at morfologik.speller.Speller.findReplacements(Speller.java:434) ~[morfologik-speller-1.10.0.jar:na]
	at com.kodcu.spell.dictionary.LanguageSpeller.findSuggestions(LanguageSpeller.java:70) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.spell.dictionary.DictionaryService.lambda$processTokens$309(DictionaryService.java:76) [AsciidocFX-1.4.5.jar:1.4.5]
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_66]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[na:1.8.0_66]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_66]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_66]
	at com.kodcu.spell.dictionary.DictionaryService.processTokens(DictionaryService.java:80) [AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.controller.ApplicationController.lambda$processTokens$147(ApplicationController.java:2067) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.service.ThreadService$1.call(ThreadService.java:39) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]


DEBUG => PDF conversion started

DEBUG => Docbook successfully validated

DEBUG => target-resolution set to: 300.0dpi (px2mm=0.08466666)

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

DEBUG => Filesystem Tree relisted for /Users/Michael/Documents/Cloud/Dropbox/sapiens/Titanium/documentation/Interactions

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Dirtab head not found.

ERROR => Dirtab hhea not found.

ERROR => Dirtab hmtx not found.

ERROR => Unknown PostScript format: 262144

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unknown PostScript format: 262144

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

ERROR => Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

DEBUG => PDF conversion ended
```

**Comment by rahmanusta** [comment]
Did you override default docbook files or settings ?

**Comment by mmatti** [comment]
Haven't touched any of the attributes/value pairs in Preview Settings, HTML Config, Docbook Settings, or Odt Settings.

Closest thing to an override has been some edits to asciidoctor-default-overrides.css.

**Comment by rahmanusta** [comment]
Hmm, Apache FOP couldn't find the fonts for any reason. It may be woth to ask it to apache fop email list, but I will upgrade the fop version, it may fix the issue.

**Comment by mmatti** [comment]
Thanks for looking into it. Will try again when the next update comes through.

**Comment by rahmanusta** [comment]
Can you try version 1.4.6 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.6 ?
