### ISSUE TITLE
Convertion to Odt fails

### ISSUE THREAD

**Issue by stasberkov** [asciidocfx/AsciidocFX#208]
Conversion to Odt fails with error. No clue what is wrong. Conversion to HTML, PDF, Docbook work ok.

```
ERROR => Problem occured while converting to ODF
java.lang.RuntimeException: java.util.concurrent.ExecutionException: netscape.javascript.JSException: Error: SyntaxError: DOM Exception 12
    at com.kodcu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:166) ~[AsciidocFX-1.4.5.jar:1.4.5]
    at com.kodcu.engine.AsciidocWebkitConverter.convertOdf(AsciidocWebkitConverter.java:191) ~[AsciidocFX-1.4.5.jar:1.4.5]
    at com.kodcu.service.convert.odf.ODFConverter.generateODFDocument(ODFConverter.java:101) ~[AsciidocFX-1.4.5.jar:1.4.5]
    at com.kodcu.controller.ApplicationController.lambda$generateODFDocument$101(ApplicationController.java:1374) [AsciidocFX-1.4.5.jar:1.4.5]
    at com.kodcu.service.ThreadService$1.call(ThreadService.java:39) ~[AsciidocFX-1.4.5.jar:1.4.5]
    at javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[jfxrt.jar:na]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_60]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_60]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_60]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[na:1.8.0_60]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_60]
    at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_60]
Caused by: java.util.concurrent.ExecutionException: netscape.javascript.JSException: Error: SyntaxError: DOM Exception 12
    at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[na:1.8.0_60]
    at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[na:1.8.0_60]
    at com.kodcu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:164) ~[AsciidocFX-1.4.5.jar:1.4.5]
    ... 13 common frames omitted
Caused by: netscape.javascript.JSException: Error: SyntaxError: DOM Exception 12
    at com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source) ~[jfxrt.jar:na]
    at com.sun.webkit.WebPage.twkExecuteScript(Native Method) ~[jfxrt.jar:na]
    at com.sun.webkit.WebPage.executeScript(Unknown Source) ~[jfxrt.jar:na]
    at javafx.scene.web.WebEngine.executeScript(Unknown Source) ~[jfxrt.jar:na]
    at com.kodcu.engine.AsciidocWebkitConverter.lambda$convert$211(AsciidocWebkitConverter.java:157) ~[AsciidocFX-1.4.5.jar:1.4.5]
    at com.kodcu.service.ThreadService.lambda$runActionLater$177(ThreadService.java:64) ~[AsciidocFX-1.4.5.jar:1.4.5]
    at com.sun.javafx.application.PlatformImpl.lambda$null$174(Unknown Source) ~[jfxrt.jar:na]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_60]
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(Unknown Source) ~[jfxrt.jar:na]
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[jfxrt.jar:na]
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:na]
    at com.sun.glass.ui.win.WinApplication.lambda$null$149(Unknown Source) ~[jfxrt.jar:na]
    ... 1 common frames omitted

```

**Comment by rahmanusta** [comment]
Hi @stasberkov , yes we should interest with the Odt output. It is now experimental, don't trust it for now :)

**Comment by stasberkov** [comment]
Anyway your tool it great!

**Comment by rahmanusta** [comment]
Thank you @stasberkov , I will interest with this feature in the future.
