### ISSUE TITLE
Error when using `:source-highlighter: coderay` and `:source-highlighter: pygments`

### ISSUE THREAD

**Issue by sboekhoff** [asciidocfx/AsciidocFX#225]
I have the following Asciidoc content:

```
= Test Extension
:toc: right
:foo-bar: Foobar
:source-highlighter: highlightjs
////
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
The valid options are coderay, highlightjs, prettify, and pygments.
In AscidocFX `coderay` and `pygments` do not work
////

== Sourcecode
{foo-bar} works

[source, php]
----
<?php 
$foo = "bar";
?>
----
```

When using `:source-highlighter: coderay`, AsciidocFX throws:
```
ERROR => {"name":"NameError","message":"uninitialized constant Object::CodeRay","line":2,"column":5745,"sourceURL":"http://localhost:37932/afx/resource/js/asciidoctor-all.js"}
```
and:
```
ERROR => Problem occured while rendering content
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Task: 9325ef7b-5474-4400-8ea5-38f01de0640b is not completed
	at com.kodcu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:166) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.engine.AsciidocWebkitConverter.convertAsciidoc(AsciidocWebkitConverter.java:181) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.controller.ApplicationController.renderLoop(ApplicationController.java:1976) [AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.controller.ApplicationController.lambda$initialize$19(ApplicationController.java:581) [AsciidocFX-1.4.5.jar:1.4.5]
	at com.kodcu.service.ThreadService$1.call(ThreadService.java:39) ~[AsciidocFX-1.4.5.jar:1.4.5]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Task: 9325ef7b-5474-4400-8ea5-38f01de0640b is not completed
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_66]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[na:1.8.0_66]
	at com.kodcu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:164) ~[AsciidocFX-1.4.5.jar:1.4.5]
	... 13 common frames omitted
Caused by: java.lang.RuntimeException: Task: 9325ef7b-5474-4400-8ea5-38f01de0640b is not completed
	at com.kodcu.controller.ApplicationController.lambda$null$138(ApplicationController.java:1917) [AsciidocFX-1.4.5.jar:1.4.5]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_66]
	at com.kodcu.controller.ApplicationController.lambda$completeWebWorkerExceptionally$139(ApplicationController.java:1916) [AsciidocFX-1.4.5.jar:1.4.5]
	... 10 common frames omitted
```
A similar error is thrown when using `:source-highlighter: pygments`

On http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/ it says that:

> The valid options are coderay, highlightjs, prettify, and pygments.

I think the preferred bahaviour should at least be a warning and the use of an alternative highlighter like

> Syntax-highligther 'coderay' not supported, using '...' instead.

**Comment by rahmanusta** [comment]
There is a limitation, Asciidoctor.js supports only highligtjs

**Comment by rahmanusta** [comment]
@sboekhoff Because Coderay depens to Ruby, Pygment depends on Python platform. For that reason, Asciidoctor.js doesn't support these syntax higlighter. If you know any way to use them in JavaScript or Java platform, I would like to support them in AsciidocFX.
