### ISSUE TITLE
PDF generation fails with "Problem selecting Match"

### ISSUE THREAD

**Issue by thoni56** [asciidocfx/AsciidocFX#284]
Running 1.5.5 on Windows I get

```
ERROR => Problem occured while selecting Match
org.xml.sax.SAXParseException: The reference to entity "lt" must end with the ';' delimiter.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at org.joox.JOOX.$(JOOX.java:268)
	at com.kodcu.other.IOHelper.$(IOHelper.java:176)
	at com.kodcu.service.convert.docbook.DocBookConverter.lambda$convert$1(DocBookConverter.java:65)
	at com.kodcu.service.ThreadService$1.call(ThreadService.java:53)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by rahmanusta** [comment]
Could you please share with me a snippet content to test this issue.

**Comment by thoni56** [comment]
I don't know what the problem is, my "snippet" is 3k lines.

`asciidoctor-pdf` fails with `invalid byte sequence in UTF-8` so it looks like it could be a non-UTF-8 character in the file, but I can't find it.

I have only edited the file with AsciidocFX 1.5.5 since it last worked to generate a PDF.

**Comment by rahmanusta** [comment]
If it is not a private content, I would like to detect what problem is.

**Comment by thoni56** [comment]
No problem, just wanted to be sure about what and how much was required.

The file is [here](https://github.com/thoni56/cgreen/blob/cgreen_value/doc/cgreen-guide-en.asciidoc). Don't know if a raw file download will give you exact the same content.

I checked it out on Linux where AsciidocFX failed the same way but `asciidoc-pdf` succeeded (which it didn't on Windows 10/Cygwin64).

**Comment by thoni56** [comment]
Sorry, about that. It was one of the included files that contained an illegal UTF-8 character.

It would be nice if AsciidocFX could hint at which file contained the offending character, though. Perhaps included that in the traceback?

**Comment by rahmanusta** [comment]
I think so, it could be a good feature
