### ISSUE TITLE
[ForkJoinPool-1-worker-4] ERROR

### ISSUE THREAD

**Issue by programaths** [asciidocfx/AsciidocFX#289]
Version : 1.5.5

AsciiDocFx turns crazy and do load of IO up to a point that whole system freeze with an SSD !

File content
```adoc
= General notes

The API is based on  http://www.jsonrpc.org/specification[JSON RPC2] protocol.

IMPORTANT: All monetary amouts are expressed ineurocents. An amount of 1.23€ is expressed as 123.

```

Log 
```log
86772 [ForkJoinPool-1-worker-4] ERROR c.k.s.dictionary.LanguageSpeller - null
java.nio.BufferOverflowException: null
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
	at morfologik.speller.Speller.findRepl(Speller.java:433)
	at morfologik.speller.Speller.findRepl(Speller.java:501)
	at morfologik.speller.Speller.findRepl(Speller.java:501)
	at morfologik.speller.Speller.findReplacements(Speller.java:411)
	at com.kodcu.spell.dictionary.LanguageSpeller.findSuggestions(LanguageSpeller.java:69)
	at com.kodcu.spell.dictionary.DictionaryService.lambda$processTokens$2(DictionaryService.java:88)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.kodcu.spell.dictionary.DictionaryService.processTokens(DictionaryService.java:92)
	at com.kodcu.controller.ApplicationController.lambda$processTokens$172(ApplicationController.java:2317)
	at com.kodcu.service.ThreadService$1.call(ThreadService.java:53)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by rahmanusta** [comment]
Hi @programaths , how frequently do you get this exception and this issue? AsciidocFX uses Morfologik for  spell checking. Sometimes this library produces BufferOverflowException.

**Comment by programaths** [comment]
I don't know. It may even be irrelevant to the exessive I/O!

**Comment by rahmanusta** [comment]
How do you measure it ? Above exception is not about IO. Could you please share your measurements.

**Comment by programaths** [comment]
I did not measure it. It's simply that when I kill AsciiDocFx, I/O disapear.
You can put this one in "to be confirmed" and I will try to first confirm it then find a way to reproduce it in a more predictive way. (Eg. automated test)

**Comment by programaths** [comment]
Hi.

Apologies for this issue. Asciidoc wasn't the culprit!!!

With iotop, I found out it was Skype Web!

So, I am closing it myself.
