### ISSUE TITLE
AsciidocFX v1.5.5 does not execute well on Mac 10.12.2

### ISSUE THREAD

**Issue by joshua60** [asciidocfx/AsciidocFX#294]
Hi All,

Tried JDK 1.7.x and 1.8.0.x, the same situation that the application UI could not show on screen but the application process is working.....

Could someone help for this?
_________________________________________________________________
#                 #   #      #                #####  #   #
  # #    ####   ###          ####   ###    ###   #       # #
 #   #  ###    #     #   #  #   #  #   #  #      ####     #
 #####    ###  #     #   #  #   #  #   #  #      #       # #
 #   #  ####    ###  #   #   ####   ###    ###   #      #   #
 ============================================================
 :: Asciidoc FX ::     (v1.5.5)

 Website: http://asciidocfx.com

[Fatal Error] autoidx-kimber.xsl:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] autoidx-kosek.xsl:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] common.xsl:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] entities.ent:16:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] l10n.dtd:1:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] l10n.xml:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] targetdatabase.dtd:4:3: The markup in the document preceding the root element must be well-formed.
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: javax.json.stream.JsonParsingException: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN]
	at com.kodcu.service.ThreadService.lambda$runActionLater$2(ThreadService.java:88)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: javax.json.stream.JsonParsingException: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN]
	at org.glassfish.json.JsonParserImpl.parsingException(JsonParserImpl.java:238)
	at org.glassfish.json.JsonParserImpl.access$1200(JsonParserImpl.java:61)
	at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:232)
	at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:101)
	at com.kodcu.config.AsciidoctorConfigBase.load(AsciidoctorConfigBase.java:189)
	at com.kodcu.config.ConfigurationService.loadConfigurations(ConfigurationService.java:62)
	at com.kodcu.boot.AppStarter.lambda$startApp$1(AppStarter.java:112)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.stage.Window.fireEvent(Window.java:1120)
	at javafx.stage.Window$9.invalidated(Window.java:818)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at com.kodcu.boot.AppStarter.lambda$startApp$3(AppStarter.java:128)
	at com.kodcu.service.ThreadService.lambda$runActionLater$2(ThreadService.java:84)
	... 4 more

**Comment by rahmanusta** [comment]
Did you modify JSON configuration files? It says there is an JSON formatting issue.

**Comment by joshua60** [comment]
there is nothing change after installation. Install it for times.....

**Comment by joshua60** [comment]
there is nothing change after installation. Install it for times.....

**Comment by rahmanusta** [comment]
So, what do you see inside USER_HOME/.AsciidocFX-1.5.5/asciidoctor_odf.json file ?

Thanks

**Comment by joshua60** [comment]
after down version, it is ok now. Thanks!

**Comment by joshua60** [comment]
Sorry to reply you for late and very thinks for your prompt support!
