### ISSUE TITLE
HTML build broken if empty setting is added

### ISSUE THREAD

**Issue by moovida** [asciidocfx/AsciidocFX#299]
In the settings under the "HTML config" tab I pushed the add button to see how it would work. It created me an empty setting pair. I didn't take care of it because I thought it would not be considered.

After that the HTML export was broken with the following stacktrace:

```
ERROR => Problem occured while converting to HTML
java.lang.NullPointerException: Name in JsonObjects name/value pair cannot be null
	at org.glassfish.json.JsonObjectBuilderImpl.validateName(JsonObjectBuilderImpl.java:158)
	at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:73)
	at com.kodcu.config.AsciidoctorConfigBase.getJSON(AsciidoctorConfigBase.java:234)
	at com.kodcu.engine.AsciidocWebkitConverter.convertHtml(AsciidocWebkitConverter.java:182)
	at com.kodcu.service.convert.html.HtmlBookConverter.convert(HtmlBookConverter.java:68)
	at com.kodcu.controller.ApplicationController.lambda$generateHtml$9(ApplicationController.java:519)
	at com.kodcu.service.ThreadService$1.call(ThreadService.java:53)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

It is not critical, but it took me a while to find out :-)

Great tool, thanks!

**Comment by rahmanusta** [comment]
Thank you dear, I would like to fix it ;)
