### ISSUE TITLE
Error Match during .epub and .pdf conversion

### ISSUE THREAD

**Issue by nelruk** [asciidocfx/AsciidocFX#311]
When I make the .html conversion, everything is OK but when I do .epub and .pdf I get this error:

```
ERROR => Problem occured while selecting Match
org.xml.sax.SAXParseException: The element type "span" must be terminated by the matching end-tag "</span>".

	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)

	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)

	at org.joox.JOOX.$(JOOX.java:268)

	at com.kodcu.other.IOHelper.$(IOHelper.java:176)

	at com.kodcu.service.convert.docbook.DocBookConverter.lambda$convert$1(DocBookConverter.java:65)

	at com.kodcu.service.ThreadService$1.call(ThreadService.java:53)

	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)

	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)

	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)

	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)

	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)




```

What does this mean? How can I fix it?

**Comment by rahmanusta** [comment]
Hi @nelruk 

Do you use html content inside your Asciidoc document?

**Comment by nelruk** [comment]
Yes @rahmanusta my cover and the titlepage is in html

**Comment by nelruk** [comment]
The error says 

> The element type "span" must be terminated

So, I made 2 revisions more inspired in @rahmanusta question and saw three <span> inside my book. That was the big problem. Thank you
