### ISSUE TITLE
AsciidocFX does not launch with Java9 due to illegal reflective access

### ISSUE THREAD

**Issue by Oliver-Loeffler** [asciidocfx/AsciidocFX#324]
Current version of Asciidoc does not start when using Java9 runtime on Windows 8.1 (x64).

```SH
> java -version
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

There is a bunch of warnings followed by a chain of exceptions. The program does not launch properly, the GUI never becomes visible but the JVM does not terminate.

Setting ``` JAVA_OPTS="--illegal-access=warn" ``` does not help, the application does not launch properly.
I did not try to enable reflective acces per library yet.

```
D:\Raumzeitfalle\blog\content\blog>asciidocfx
   #                 #   #      #                #####  #   #
  # #    ####   ###          ####   ###    ###   #       # #
 #   #  ###    #     #   #  #   #  #   #  #      ####     #
 #####    ###  #     #   #  #   #  #   #  #      #       # #
 #   #  ####    ###  #   #   ####   ###    ###   #      #   #
 ============================================================
 :: Asciidoc FX ::     (v1.5.6)

 Website: http://asciidocfx.com

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/D:/Raumzeitfalle/AsciidocFX/target/appassembler/lib/spring-core-4.3.11.RELEASE.jar) to method java.
lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[Fatal Error] autoidx-kimber.xsl:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] autoidx-kosek.xsl:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] common.xsl:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] entities.ent:16:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] l10n.dtd:1:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] l10n.xml:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] targetdatabase.dtd:4:3: The markup in the document preceding the root element must be well-formed.
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/css/converters/SizeConverter
        at org.kordamp.ikonli.javafx.FontIcon$StyleableProperties.<clinit>(FontIcon.java:245)
        at org.kordamp.ikonli.javafx.FontIcon.getClassCssMetaData(FontIcon.java:301)
        at org.kordamp.ikonli.javafx.FontIcon.getCssMetaData(FontIcon.java:305)
        at javafx.graphics/javafx.scene.CssStyleHelper$CacheContainer.<init>(Unknown Source)
        at javafx.graphics/javafx.scene.CssStyleHelper$CacheContainer.<init>(Unknown Source)
        at javafx.graphics/javafx.scene.CssStyleHelper.createStyleHelper(Unknown Source)
        at javafx.graphics/javafx.scene.Node.reapplyCss(Unknown Source)
        at javafx.graphics/javafx.scene.Node.reapplyCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Node.invalidatedScenes(Unknown Source)
        at javafx.graphics/javafx.scene.Node.setScenes(Unknown Source)
        at javafx.graphics/javafx.scene.Parent$2.onChanged(Unknown Source)
        at javafx.base/com.sun.javafx.collections.TrackableObservableList.lambda$new$0(Unknown Source)
        at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
        at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
        at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)
        at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)
        at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
        at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)
        at javafx.base/javafx.collections.ModifiableObservableListBase.setAll(Unknown Source)
        at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
        at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
        at javafx.controls/javafx.scene.control.skin.LabeledSkinBase.updateChildren(Unknown Source)
        at javafx.controls/javafx.scene.control.skin.LabeledSkinBase.<init>(Unknown Source)
        at javafx.controls/javafx.scene.control.skin.LabelSkin.<init>(Unknown Source)
        at javafx.controls/javafx.scene.control.Label.createDefaultSkin(Unknown Source)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Unknown Source)
        at javafx.controls/javafx.scene.control.Control.access$000(Unknown Source)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.access$400(Unknown Source)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(Unknown Source)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Unknown Source)
        at javafx.controls/javafx.scene.control.Control.access$000(Unknown Source)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.access$400(Unknown Source)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.access$400(Unknown Source)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.access$400(Unknown Source)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.access$400(Unknown Source)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(Unknown Source)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Unknown Source)
        at javafx.controls/javafx.scene.control.Control.access$000(Unknown Source)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.access$400(Unknown Source)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.access$400(Unknown Source)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(Unknown Source)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Unknown Source)
        at javafx.controls/javafx.scene.control.Control.access$000(Unknown Source)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.access$400(Unknown Source)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Parent.access$400(Unknown Source)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Node.processCSS(Unknown Source)
        at javafx.graphics/javafx.scene.Scene.doCSSPass(Unknown Source)
        at javafx.graphics/javafx.scene.Scene.preferredSize(Unknown Source)
        at javafx.graphics/javafx.scene.Scene$2.preferredSize(Unknown Source)
        at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(Unknown Source)
        at javafx.graphics/javafx.stage.Window$12.invalidated(Unknown Source)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
        at javafx.graphics/javafx.stage.Window.setShowing(Unknown Source)
        at javafx.graphics/javafx.stage.Window.show(Unknown Source)
        at javafx.graphics/javafx.stage.Stage.show(Unknown Source)
        at com.kodedu.boot.AppStarter.lambda$5(AppStarter.java:128)
        at com.kodedu.service.ThreadService.lambda$2(ThreadService.java:79)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.converters.SizeConverter
```

**Comment by rahmanusta** [comment]
It doesn't support J9 yet, but we have a branch for that https://github.com/asciidocfx/AsciidocFX/tree/java9-latest

**Comment by rahmanusta** [comment]
Can you please try v1.7.0 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.0 ?

**Comment by Oliver-Loeffler** [comment]
Cool. I will try this out.

**Comment by rahmanusta** [comment]
Hi, could you please reinstall https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.4 and check?
