### ISSUE TITLE
little help on installing asciidocFX project

### ISSUE THREAD

**Issue by lesar** [asciidocfx/AsciidocFX#333]
I have cloned the project  
I have installed this Scene Builder:  
```
Product Version
JavaFX Scene Builder 8.4.1

Build Information
Version 8.4.1
Date: 2017-10-17
Java Version: 1.8.0_144-b01, Oracle Corporation

Logging
The default configuration stores logging output in a file named scenebuilder-8.4.1.log (possibly followed by a trailing '.' and a digit).
The default file path is /tmp/scenebuilder-8.4.1.log

JavaFX
Toolkit = QuantumToolkit
Pipeline = ES2Pipeline
Hardware acceleration ENABLED

Java
1.8.0_144-b01, Oracle Corporation

Operating System
Linux, amd64, 4.4.0-101-generic

Copyright (c) 2015-2017, Gluon.
```

on my system Ubuntu 16.04 64bit I have `openjdk version "1.8.0_151`  

if I try to open Scene.fxml I get this error:
```
java.io.IOException: javafx.fxml.LoadException: 
/home/leonardo/sviluppo/applicazioni/asciidocfx/AsciidocFX/src/main/resources/fxml/Scene.fxml

	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:98)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:85)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:102)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.updateFxomDocument(EditorController.java:2540)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.setFxmlTextAndLocation(EditorController.java:761)
	at com.oracle.javafx.scenebuilder.app.DocumentWindowController.loadFromFile(DocumentWindowController.java:385)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performOpenFiles(SceneBuilderApp.java:665)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.handleOpenFilesAction(SceneBuilderApp.java:510)
	at com.oracle.javafx.scenebuilder.app.AppPlatform$MessageBoxDelegate.lambda$messageBoxDidGetMessage$0(AppPlatform.java:189)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javafx.fxml.LoadException: 
/home/leonardo/sviluppo/applicazioni/asciidocfx/AsciidocFX/src/main/resources/fxml/Scene.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2848)
	at javafx.fxml.FXMLLoader.processImport(FXMLLoader.java:2692)
	at javafx.fxml.FXMLLoader.processProcessingInstruction(FXMLLoader.java:2661)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2517)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:93)
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.kodedu.component.ShowerHider
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at javafx.fxml.FXMLLoader.loadTypeForPackage(FXMLLoader.java:2916)
	at javafx.fxml.FXMLLoader.loadType(FXMLLoader.java:2905)
	at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2846)
	... 20 more
```

Have you any idea on what's the problem?

regards,
Leonardo

**Comment by rahmanusta** [comment]
After building AsciidocFX, you should add required component to classpath in Scene Builder. Actually, you don't need Scene Builder. You can directly edit FXML files.

**Comment by lesar** [comment]
Tanks very much  rahmanusta.  
If I wont to open Scene.fxml on scenebuilder,  
on my pc an ubuntu 16.04 I have to edit /opt/scenebuilder/app/SceneBuilder.cfg
and change app.classpath=/home/.../AshidocFX/target/classes  
(I have compile all before edit)  
Then open scenebuilder open Library editor and add  

- org.kordamp.ikonli:ikonli-javafx:2.1.0
- org.kordamp.ikonli:ikonli-fontawesome-pack:2.1.0  

after this changes I can open Scene.fxml in scenebuilder and work by double click on Netbeans too  
I hope that in the future Netbeans can do it automatically without manual change.  

regards,
Leonardo
