### ISSUE TITLE
Problems with docinfo. files

### ISSUE THREAD

**Issue by pkuenemann** [asciidocfx/AsciidocFX#409]
Hi,

I am using AsciiDocFX with AsciiDoc Version 1.5.5 and try to insert my own footer to the generated html-files. For that I place the :docinfo: shared statement on the top of my adoc-file:

```
= Info-Letter Tattoo&Piercing-Studios
:docinfo: shared
:docinfodir: ./meta

image::../images/newsletter-yogi.jpg[align="center"]
```

And place the files docinfo.html and docinfo-footer.html in the named './meta' directory

docinfo.html:
```
<style>
.footer-text { color: rgba(255,255,255,.8); }
</style>
```
docinfo-footer.html:
```
<p class="footer-text">
<a href="https://www.kisscal.tattoo/datenschutz.html">Datenschutz</a>
<a href="https://www.kisscal.tattoo/impressum.html">Impressum</a>
</p>
```

When I now try to save the adoc file as HTML-File, nothing happenes. The file will not be created. When I change the :docinfo: to 'private' and rename the docinfo-files, the html.file can be generated but does not show my own footer.

In another issue I found that I should change the safe-mode to UNSAFE, I do not know how, though. I would appreaciate any help.

Thanx and best regards,
Peter.

**Comment by rahmanusta** [comment]
It is not supported in this version. It can be supported in next release.

**Comment by pkuenemann** [comment]
Hello Rahman, can you estimate, when the next release will be available? I am also still waiting for the integration of the latest version of asciidoc into asciidocFx to be able to change the favicon. (See my issue from Oct. 2018 #394)

**Comment by lopsotronic** [comment]
Seconding request for support of docinfo.xml files, particularly for ability to inject legalnotice into the publishing pipeline.

**Comment by pkuenemann** [comment]
It looks like in Version 1.7.3 of AsciiDocFX, which I am using now, the docinfo files are supported. Unfortunatelly I am running on an exception when I try to use docinfo.html files.

I add the following line to my asciidoc:

:docinfo: shared

The docinfo.html looks like this:

<meta name="robots" contant="noindex, nofollow">

When I try to save the asciidoc as an Html File, I run into the following errors:

DEBUG => HTML conversion started

ERROR => {name:SecurityError,line:413,column:84,sourceURL:http://localhost:59491/afx/resource/js/?p=js/asciidoctor-browser.js}

ERROR => {name:SecurityError,line:413,column:84,sourceURL:http://localhost:59491/afx/resource/js/?p=js/asciidoctor-browser.js}

ERROR => Problem occured while converting to HTML
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Task: 8b6650d6-9806-4e85-882d-7a155a51e854 is not completed
	at com.kodedu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:150)
	at com.kodedu.engine.AsciidocWebkitConverter.convertHtml(AsciidocWebkitConverter.java:195)
	at com.kodedu.service.convert.html.HtmlBookConverter.convert(HtmlBookConverter.java:72)
	at com.kodedu.controller.ApplicationController.lambda$generateHtml$9(ApplicationController.java:516)
	at com.kodedu.service.ThreadService$1.call(ThreadService.java:48)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1406)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Task: 8b6650d6-9806-4e85-882d-7a155a51e854 is not completed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2093)
	at com.kodedu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:148)
	... 12 common frames omitted
Caused by: java.lang.RuntimeException: Task: 8b6650d6-9806-4e85-882d-7a155a51e854 is not completed
	at com.kodedu.controller.ApplicationController.lambda$completeWebWorkerExceptionally$171(ApplicationController.java:2304)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.kodedu.controller.ApplicationController.lambda$completeWebWorkerExceptionally$172(ApplicationController.java:2303)
	... 9 common frames omitted

Any ideas?

**Comment by pkuenemann** [comment]
Since it seems to be a new issue (new version of AsciiDoc), I rather put the error in a new issue.
