### ISSUE TITLE
Problem when taming SVG images

### ISSUE THREAD

**Issue by mvisaweevil** [asciidocfx/AsciidocFX#422]
**The following syntax (using opts) triggs an error.
image::MYLOGO.svg[height=10%,width=10%,align="left",opts=inline]

Removing opts part makes it running perfectly.

Could you also providing 1.7.0 version package without jre ?**

ERROR => Problem occured while rendering content
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Task: c1848891-01be-44c6-aca5-0c5eb9e065ac is not completed
	at com.kodedu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:159)
	at com.kodedu.engine.AsciidocWebkitConverter.convertAsciidoc(AsciidocWebkitConverter.java:174)
	at com.kodedu.controller.ApplicationController.renderLoop(ApplicationController.java:2367)
	at com.kodedu.controller.ApplicationController.lambda$initializeApp$18(ApplicationController.java:613)
	at com.kodedu.service.ThreadService$1.call(ThreadService.java:48)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Task: c1848891-01be-44c6-aca5-0c5eb9e065ac is not completed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.kodedu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:157)
	... 11 common frames omitted
Caused by: java.lang.RuntimeException: Task: c1848891-01be-44c6-aca5-0c5eb9e065ac is not completed
	at com.kodedu.controller.ApplicationController.lambda$null$171(ApplicationController.java:2312)
	at java.util.Optional.ifPresent(Unknown Source)
	at com.kodedu.controller.ApplicationController.lambda$completeWebWorkerExceptionally$172(ApplicationController.java:2311)
	... 8 common frames omitted

**Comment by rahmanusta** [comment]
Hi, use single colon image:MYLOGO.svg[height=10%,width=10%,align="left"] for inline image

**Comment by mvisaweevil** [comment]
OK thanks, but I use and write asciidoctor files that can be used in other environments (i.e. under linux, with native asciidoctor toolchain). So, does it means that the syntax "image::sample.svg[Embedded,300,opts=inline]" from asciidoctor's user'sguide "29.4. Taming SVGs chapter" is not supported ?

**Comment by rahmanusta** [comment]
Sorry, I was not aware this concept :) Edit $HOME/.AsciidocFX-1.7.0/asciidoctor_preview.json file, and set "safe": "unsafe", it resolve your issue.
