### ISSUE TITLE
Unable to save pdf file

### ISSUE THREAD

**Issue by siddjain** [asciidocfx/AsciidocFX#429]
Hello, I installed AsciidocFX on Mac OSX High Sierra but when I try to save an asciidoc as PDF I don't see any output file. And I see an error in the log:

> ERROR => {name:RuntimeError,message:{$$id:4}}

there is no more information. In the preview pane I can see the doc rendered but math symbols don't display. wondering if anyone could help with this. thanks

**Comment by siddjain** [comment]
found the logs at /Users/sjain68/Applications/AsciidocFX/log/asciidocfx.log. i have pasted them here:
https://gist.github.com/siddjain/68665f114f7d7a00b8c8ec293023b575

this is the stacktrace:

```
9338713 [JavaFX Application Thread] ERROR c.k.c.ApplicationController - {name:RuntimeError,message:{$$id:4}} 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Task: 5f307513-b7ea-4712-a267-5b9fcbc01a0a is not completed
	at com.kodedu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:146)
	at com.kodedu.engine.AsciidocWebkitConverter.convertDocbook(AsciidocWebkitConverter.java:178)
	at com.kodedu.service.convert.docbook.DocBookConverter.lambda$convert$1(DocBookConverter.java:57)
	at com.kodedu.service.ThreadService$1.call(ThreadService.java:48)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1406)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Task: 5f307513-b7ea-4712-a267-5b9fcbc01a0a is not completed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2093)
	at com.kodedu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:144)
	... 11 more
Caused by: java.lang.RuntimeException: Task: 5f307513-b7ea-4712-a267-5b9fcbc01a0a is not completed
	at com.kodedu.controller.ApplicationController.lambda$completeWebWorkerExceptionally$171(ApplicationController.java:2304)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.kodedu.controller.ApplicationController.lambda$completeWebWorkerExceptionally$172(ApplicationController.java:2303)
	... 9 more
```

**Comment by rahmanusta** [comment]
Hi, can you share your document to check?

**Comment by siddjain** [comment]
see attached. rename it to test.adoc. Its the stem processor that's causing it to fail.
[test.txt](https://github.com/asciidocfx/AsciidocFX/files/3444519/test.txt)

**Comment by siddjain** [comment]
is stem not recognized by asciidocfx? how do i display inline math in asciidocfx?

**Comment by rahmanusta** [comment]
Hey, try https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.1

**Comment by siddjain** [comment]
Thanks. I tried it. The error is gone but AsciiDocFX is not able to parse stem blocks that have greek letters in them. This is on Windows.

________________________________

**Comment by siddjain** [comment]
ping..

________________________________

**Comment by rahmanusta** [comment]
Was it working in v1.6.9? I need an example file.

**Comment by siddjain** [comment]
the example file test.txt is attached to this thread. Rename it to test.adoc. here is a link to it: https://github.com/asciidocfx/AsciidocFX/files/3444519/test.txt

**Comment by rahmanusta** [comment]
I have no problem when converting PDF. Can you re-install https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.1 ?

```
= Chapter 1
:stem:
:chapter: 1
:sectnums:

== What is Foo?

stem:[Δ δ]

Δ δ
```

[demo.pdf](https://github.com/asciidocfx/AsciidocFX/files/3488755/demo.pdf)

**Comment by siddjain** [comment]
It doesn't work for me. Is there any other software I need to install to use asciidoc fx?
