### ISSUE TITLE
Tree diagram not being generated

### ISSUE THREAD

**Issue by ellipticview** [asciidocfx/AsciidocFX#440]
Syntax:
````
[tree,file="tree.png"]
--
api
|--credentials
|--generic
`--abc.doc
--
````

the png file does not get generated. Logfile contains:

````
68563 [JavaFX Application Thread] ERROR com.kodedu.boot.AppStarter - netscape.javascript.JSException: ReferenceError: Can't find variable: refreshUI
java.lang.RuntimeException: netscape.javascript.JSException: ReferenceError: Can't find variable: refreshUI
	at com.kodedu.service.ThreadService.lambda$runActionLater$2(ThreadService.java:83)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: netscape.javascript.JSException: ReferenceError: Can't find variable: refreshUI
	at javafx.web/com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:157)
	at javafx.web/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at javafx.web/com.sun.webkit.WebPage.executeScript(WebPage.java:1513)
	at javafx.web/javafx.scene.web.WebEngine.executeScript(WebEngine.java:972)
	at com.kodedu.component.HtmlPane.lambda$refreshUI$0(HtmlPane.java:56)
	at com.kodedu.service.ThreadService.lambda$runActionLater$2(ThreadService.java:79)
	... 7 common frames omitted

````

**Comment by rahmanusta** [comment]
I have checked. Which version do you use? It looks working: 
![Screen Shot 2019-09-10 at 12 33 14](https://user-images.githubusercontent.com/1158804/64606743-3acd5a80-d3c7-11e9-958a-801e31846ab0.png)

**Comment by bcouetil** [comment]
I experience the same problem with this version. I'm on Windows with MSI installation

This was working in a previous version (about 6 months ago), did not try since.

The missing variable is different :

```
ERROR => netscape.javascript.JSException: ReferenceError: Can't find variable: c3
java.lang.RuntimeException: netscape.javascript.JSException: ReferenceError: Can't find variable: c3
	at com.kodedu.service.ThreadService.lambda$runActionLater$2(ThreadService.java:83)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: netscape.javascript.JSException: ReferenceError: Can't find variable: c3
	at javafx.web/com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:157)
	at javafx.web/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at javafx.web/com.sun.webkit.WebPage.executeScript(WebPage.java:1513)
	at javafx.web/javafx.scene.web.WebEngine.executeScript(WebEngine.java:972)
```

Do I have to install some specific java version ?

**Comment by CsrRk** [comment]
I experience the same here, with the version 1.7.1 too, and openjdk 12.0.1.

**Comment by bcouetil** [comment]
It seems to work on Ubuntu. Must be a Windows problem !

**Comment by naltatis** [comment]
> It seems to work on Ubuntu. Must be a Windows problem !
and macOS, since it also doesn't work for me ;)
