### ISSUE TITLE
Errors using docinfo files with AsciiDoc

### ISSUE THREAD

**Issue by pkuenemann** [asciidocfx/AsciidocFX#481]
I am using Version 1.7.3 of AsciiDocFX, which now supports the docinfo files. Unfortunatelly I am running on an exception when I try to use docinfo.html files.

I add the following line to my asciidoc:

:docinfo: shared

The docinfo.html looks like this:

<meta name="robots" content=„noindex, nofollow">

When I try to save the asciidoc as an Html File, I run into the following errors:

```
DEBUG => HTML conversion started

ERROR => {name:SecurityError,line:413,column:84,sourceURL:http://localhost:59491/afx/resource/js/?p=js/asciidoctor-browser.js}

ERROR => {name:SecurityError,line:413,column:84,sourceURL:http://localhost:59491/afx/resource/js/?p=js/asciidoctor-browser.js}

ERROR => Problem occured while converting to HTML
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Task: 8b6650d6-9806-4e85-882d-7a155a51e854 is not completed
at com.kodedu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:150)
at com.kodedu.engine.AsciidocWebkitConverter.convertHtml(AsciidocWebkitConverter.java:195)
at com.kodedu.service.convert.html.HtmlBookConverter.convert(HtmlBookConverter.java:72)
at com.kodedu.controller.ApplicationController.lambda$generateHtml$9(ApplicationController.java:516)
at com.kodedu.service.ThreadService$1.call(ThreadService.java:48)
at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1406)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Task: 8b6650d6-9806-4e85-882d-7a155a51e854 is not completed
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2093)
at com.kodedu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:148)
... 12 common frames omitted
Caused by: java.lang.RuntimeException: Task: 8b6650d6-9806-4e85-882d-7a155a51e854 is not completed
at com.kodedu.controller.ApplicationController.lambda$completeWebWorkerExceptionally$171(ApplicationController.java:2304)
at java.base/java.util.Optional.ifPresent(Optional.java:183)
at com.kodedu.controller.ApplicationController.lambda$completeWebWorkerExceptionally$172(ApplicationController.java:2303)
... 9 common frames omitted

```
Any ideas?

**Comment by rahmanusta** [comment]
I believe now it should work as expected.

**Comment by pkuenemann** [comment]
...yes, it does now, thank you. You can close the issue.
 
Greetings, Peter.
