### ISSUE TITLE
Can't Generate PDF with windows restricted filename characters in title 

### ISSUE THREAD

**Issue by bblonski** [asciidocfx/AsciidocFX#49]
AsciidocFX silently fails to generate a PDF document on windows if I have the colon `:` character in the title of the document.  Windows does not allow the `:` character in file names, so a substitution or error message would be expected. Log file has the following stack trace.

```
123361 [XNIO-2 I/O-3] ERROR org.xnio.listener - XNIO001007: A channel event listener threw an exception
java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating
	at org.xnio.nio.WorkerThread.execute(WorkerThread.java:568) [AsciidocFX-1.3.2.jar:na]
	at io.undertow.websockets.jsr.UndertowSession$2.handleEvent(UndertowSession.java:111) ~[AsciidocFX-1.3.2.jar:na]
	at io.undertow.websockets.jsr.UndertowSession$2.handleEvent(UndertowSession.java:103) ~[AsciidocFX-1.3.2.jar:na]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[AsciidocFX-1.3.2.jar:na]
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:842) ~[AsciidocFX-1.3.2.jar:na]
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:776) ~[AsciidocFX-1.3.2.jar:na]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[AsciidocFX-1.3.2.jar:na]
	at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.terminated(WriteReadyHandler.java:70) ~[AsciidocFX-1.3.2.jar:na]
	at org.xnio.nio.NioSocketConduit.writeTerminated(NioSocketConduit.java:197) [AsciidocFX-1.3.2.jar:na]
	at org.xnio.nio.NioSocketConduit.terminateWrites(NioSocketConduit.java:186) [AsciidocFX-1.3.2.jar:na]
	at org.xnio.nio.NioSocketConduit.truncateWrites(NioSocketConduit.java:191) [AsciidocFX-1.3.2.jar:na]
	at io.undertow.conduits.IdleTimeoutConduit.truncateWrites(IdleTimeoutConduit.java:306) [AsciidocFX-1.3.2.jar:na]
	at org.xnio.conduits.ConduitStreamSinkChannel.close(ConduitStreamSinkChannel.java:186) [AsciidocFX-1.3.2.jar:na]
	at org.xnio.IoUtils.safeClose(IoUtils.java:134) [AsciidocFX-1.3.2.jar:na]
	at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.forceTermination(WriteReadyHandler.java:57) ~[AsciidocFX-1.3.2.jar:na]
	at org.xnio.nio.NioSocketConduit.forceTermination(NioSocketConduit.java:107) [AsciidocFX-1.3.2.jar:na]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:490) [AsciidocFX-1.3.2.jar:na]
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: TypeError: 'undefined' is not a function (evaluating 'b.$rpartition(": ")')
	at com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(Unknown Source)
	at javafx.scene.web.WebEngine.executeScript(Unknown Source)
	at com.kodcu.service.convert.RenderService.lambda$null$104(RenderService.java:92)
	at com.kodcu.service.convert.RenderService$$Lambda$498/1238677787.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$48/356029151.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$47/198305255.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$$Lambda$38/126214382.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Warning: Could not get charToByteConverterClass!
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: TypeError: 'undefined' is not a function (evaluating 'b.$rpartition(": ")')
	at com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(Unknown Source)
	at javafx.scene.web.WebEngine.executeScript(Unknown Source)
	at com.kodcu.service.convert.RenderService.lambda$null$104(RenderService.java:92)
	at com.kodcu.service.convert.RenderService$$Lambda$498/1238677787.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$48/356029151.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$47/198305255.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$$Lambda$38/126214382.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by rahmanusta** [comment]
It is not about filename issue, Asciidoctor.js doesnt like : character in title unfortunately. So, remove it or open an issue on https://github.com/asciidoctor/asciidoctor.js

**Comment by bblonski** [comment]
Tried this in asciidoctor.js and it works fine.  It also works in the live preview and when exporting to html.  It seems to mainly affect PDF generation.  Docbook generation creates an empty file.  I think maybe it's a bug in the Apache FOP integration?  At the very least it should handle the exception gracefully instead of silently failing.  Can you take another look at it?

**Comment by rahmanusta** [comment]
I will look it again

**Comment by rahmanusta** [comment]
@bblonski can you try to generate docbook with asciidoctor.js ?

**Comment by rahmanusta** [comment]
Any good news? @bblonski

**Comment by bblonski** [comment]
Sorry, I forgot to get back to you.  It sounds like the asciidoctor.js devs
were able to reproduce this so it's probably on their end.
