### ISSUE TITLE
EPUB generation not working in v1.7.4

### ISSUE THREAD

**Issue by Thanatermesis** [asciidocfx/AsciidocFX#516]
I just downgraded to 1.7.3 that the EPUB rendering works correctly, it doesn't works on 1.7.4, tested on Debian stable codename Buster

**Comment by rahmanusta** [comment]
Hi, thanks for reporting. We noticed the issue and fix it soon. New release will be provided.

**Comment by rahmanusta** [comment]
Hi, could you please reinstall https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.4 and check?

**Comment by Thanatermesis** [comment]
Ok, I just tried and the bug is not fixed, but I wanted also to report a few more things found:

### Perrmissions issue due to using system files:

* first of all, I tried to simply open it and generate an epub with the provided, but it show me this error:

```
ERROR => Problem occured while moving /tmp/epub13349130918117519979/book.epub to /usr/share/AsciidocFX/conf/Support.epub
java.nio.file.AccessDeniedException: /tmp/epub13349130918117519979/book.epub -> /usr/share/AsciidocFX/conf/Support.epub
	at...
```
this error is not the real cause but I wanted to report it too, so the tarball was installed on the system and by root, these files should not be used in write mode (instead, using user's files or its own cache files) and thus that's why it errors

### CopyPaste problem

* So then I tried to copy-paste the page in a New project, using "ctrl + c, ctrl + v", but nothing was copy-pasted (i needed to select these features from the menus)

### Epub export issue:

* so there's the real issue with the epub generation:

```

ERROR => Problem occured while converting to Epub
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at com.kodedu.service.convert.ebook.EpubConverter.produceEpub3(EpubConverter.java:83)
	at com.kodedu.service.convert.ebook.EpubConverter.produceEpub3(EpubConverter.java:76)
	at com.kodedu.controller.ApplicationController.lambda$convertEpub$7(ApplicationController.java:466)
	at com.kodedu.controller.ApplicationController$$Lambda$2265/0x0000000083248848.run(Unknown Source)
	at com.kodedu.service.ThreadService$1.call(ThreadService.java:48)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1414)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

_Tested with other exporters (except Mobi, because of lack of kindlegen executable) and all the others worked_

Thank you

**Comment by rahmanusta** [comment]
Can you run epub generation but some other file than Support.adoc like Cheatsheet.adoc? Config folder may not have permission to create.

I fixed the copy file issue, it was exist only for read only files like Support.adoc.

Hi, could you please reinstall https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.4 and check ?

**Comment by Thanatermesis** [comment]
Thanks for the update, the last one CORRECTLY generates the epub files now :)

I did it with Cheatsheet.adoc and it worked, but unfortunately it lacked a few images from the markup in the resulting epub:

![image](https://user-images.githubusercontent.com/1181626/116787797-8f46b180-aaa6-11eb-9286-22ab56eb1c20.png)

_other images like the Chart / Statistics worked correctly_

**Comment by rahmanusta** [comment]
That’s great, as I remember we didn’t implement admonitions image for epub. Thank you for rising the issue and helping to verify 👍
