### ISSUE TITLE
NPE when start up

### ISSUE THREAD

**Issue by yinabameguru** [asciidocfx/AsciidocFX#522]
log:

 ============================================================
 :: Asciidoc FX ::     (v1.7.4)

 Website: http://asciidocfx.com

3642 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 'webSocketHandlerMapping' {/ws/**=org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler@5de172d0, /ws**/**=org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler@dbbf3396, /ws/**/**=org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler@a841c29b} 
3733 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 
	c.k.c.SlideResource:
	{[GET, HEAD, OPTIONS, POST] [/afx/slide || /afx/slide/** || /afx/slide/*.*], consumes [*/*], produces [*/*]}: onrequest(HttpServletRequest,HttpServletResponse,String,String) 
3735 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 
	c.k.c.DataUriController:
	{[HEAD, OPTIONS, POST] [/read-data-uri], consumes [*/*], produces [*/*]}: readUri(String,String) 
3735 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 
	c.k.c.CacheResource:
	{[GET, HEAD, OPTIONS, POST] [/afx/cache || /afx/cache/** || /afx/cache/*.*], consumes [*/*], produces [*/*]}: executeCachedResource(HttpServletRequest,HttpServletResponse) 
3736 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 
	c.k.c.LiveResource:
	{[GET, HEAD, OPTIONS, POST] [/afx/live || /afx/live/** || /afx/live/*.*], consumes [*/*], produces [*/*]}: onrequest(HttpServletRequest,HttpServletResponse,String) 
3736 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 
	c.k.c.CommonResource:
	 
3736 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 
	c.k.c.DynamicResource:
	{[GET, HEAD, OPTIONS, POST] [/afx/dynamic || /afx/dynamic/** || /afx/dynamic/*.*], consumes [*/*], produces [*/*]}: onrequest(HttpServletRequest,HttpServletResponse,String) 
3736 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 
	c.k.c.GeneralResource:
	{[GET, HEAD, OPTIONS, POST] [/afx/resource || /afx/resource/** || /afx/resource/*.*], consumes [*/*], produces [*/*]}: onrequest(HttpServletRequest,HttpServletResponse,String) 
3737 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 
	c.k.c.JadeResource:
	{[GET, HEAD, OPTIONS, POST] [/afx/jade || /afx/jade/** || /afx/jade/*.*], consumes [*/*], produces [*/*]}: onrequest(HttpServletRequest,HttpServletResponse,String) 
3737 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 
	c.k.c.WebWorkerResource:
	{[GET, HEAD, OPTIONS, POST] [/afx/worker/ || /afx/worker/** || /afx/worker/*.*], consumes [*/*], produces [*/*]}: onrequest(HttpServletRequest,HttpServletResponse,String) 
3737 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 
	c.k.c.EpubResource:
	{[GET, HEAD, OPTIONS, POST] [/afx/epub || /afx/epub/** || /afx/epub/*.*], consumes [*/*], produces [*/*]}: onrequest(HttpServletRequest,HttpServletResponse,String) 
3738 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 
	c.k.c.AllController:
	{[GET, HEAD, OPTIONS, POST] [/**/*.* || /*.*], consumes [*/*], produces [*/*]}: all(HttpServletRequest,HttpServletResponse) 
3739 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 
	o.s.b.a.w.s.e.BasicErrorController:
	{ [/error], produces [text/html]}: errorHtml(HttpServletRequest,HttpServletResponse)
	{ [/error]}: error(HttpServletRequest) 
3747 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 'beanNameHandlerMapping' {} 
3754 [Thread-8] DEBUG _.s.w.s.HandlerMapping.Mappings - 'resourceHandlerMapping' {/webjars/**=ResourceHttpRequestHandler [Classpath [META-INF/resources/webjars/]], /**=ResourceHttpRequestHandler [Classpath [META-INF/resources/], Classpath [resources/], Classpath [static/], Classpath [public/], ServletContext [/]]} 
[Fatal Error] autoidx-kimber.xsl:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] autoidx-kosek.xsl:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] common.xsl:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] entities.ent:16:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] l10n.dtd:1:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] l10n.xml:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] targetdatabase.dtd:4:3: The markup in the document preceding the root element must be well-formed.
5762 [Thread-10] INFO  com.kodedu.service.PathMapper - Indexing.. C:\Users\meguru\Desktop\fdd 
5770 [Thread-10] INFO  com.kodedu.service.PathMapper - Indexing completed.. C:\Users\meguru\Desktop\fdd 
java.lang.NullPointerException: Cannot invoke "com.sun.prism.RTTexture.contentsUseful()" because "this.texture" is null
	at javafx.web/com.sun.javafx.webkit.prism.WCPageBackBufferImpl.validate(WCPageBackBufferImpl.java:102)
	at javafx.web/com.sun.webkit.WebPage.paint(WebPage.java:698)
	at javafx.web/com.sun.javafx.sg.prism.web.NGWebView.renderContent(NGWebView.java:95)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2313)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2207)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2233)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2066)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2313)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2207)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2233)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2066)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:479)
	at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:328)
	at javafx.graphics/com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at javafx.graphics/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:853)

**Comment by Ayowel** [comment]
Hi,

Is it a new AsciidocFX install or an update from a previous version ?

Are you using a professionnal/hardened workstation ? AsciidocFX starts a local server and needs to open a port to do so. Depending on your workstation's configuration, it might be forbidden by the OS or unreachable by the client part of the app

**Comment by yinabameguru** [comment]
It occurs on a new installed AsciidocFX. And I'm use a ordinary Win10 PC.
I solved this problem a few days ago by deleting C:\Users\username\.AsciidocFX-1.7.4
But I often start Java server on my computer. Could it be because the port is occupied?

**Comment by Ayowel** [comment]
Seems likely. AsciidocFX opens the port 8080 by default. Looking at the source code, you should be able to change this behavior by adding a line such as `-Dlocal.server.port=8085` (to set the port to `8085`) in `AsciidocFX.vmoptions` in your installation directory

**Comment by yinabameguru** [comment]
OK.
Thanks!
