### ISSUE TITLE
Add instructions for extensions

### ISSUE THREAD

**Issue by GregJohnStewart** [asciidocfx/AsciidocFX#612]
There should be improved docs for how to install extensions. It is not obvious how to get them installed.

For example, PlantUML. All that is provided is a link, but no context on how it needs to be installed for AsciidocFX. I tried the linked docs, using `gem install asciidoctor-diagram`, but no joy. 

If there is a folder where a jar needs placed, then that needs to be explicitly mentioned.

**Comment by gillesB** [comment]
I certainly get your point, nevertheless I am a bit confused by your example, because PlantUML should work out of the box.

**Comment by GregJohnStewart** [comment]
Ah good point. Sorry, looks like syntax might have changed since I last had this asciidoc open (it's been a couple years)? ditaa and uml seem to be working after all.

Might be good to explicitly note which extensions are pre-installed, and which need extra work?

**Comment by life888888** [comment]
# install mmdc
## open terminal and run command
```
sudo npm install -g @mermaid-js/mermaid-cli
```

## test mmdc version
```
$ mmdc --version
10.6.1
```

## test mmdc with no parameter
```
$ mmdc

No input file specified, reading from stdin. If you want to specify an input file, please use `-i <input>.` You can use `-i -` to read from stdin and to suppress this warning.


Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/demouser1/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:263:27)
    at ChromeLauncher.executablePath (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:176:25)
    at ChromeLauncher.computeLaunchArguments (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:93:37)
    at async ChromeLauncher.launch (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:57:28)
    at async run (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:404:19)
    at async cli (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:184:3)
```

## find google chrome location
```
$ which google-chrome
/usr/bin/google-chrome
```

## Edit your .bashrc file

Add this line to your `.bashrc` file then save it.

```
export PUPPETEER_EXECUTEABLE_PATH=/usr/bin/google-chrome
```

then logout and login again or reboot.


## test mmdc with no parameter again
```
$ mmdc
No input file specified, reading from stdin. If you want to specify an input file, please use `-i <input>.` You can use `-i -` to read from stdin and to suppress this warning.

````
(No error message)
Exit with `Ctrl` +` C` 

## create test file

`input.mmd`

```
graph
   accTitle: My title here
   accDescr: My description here
   A-->B
```   

## Run test mmdc

```
$ mmdc -i input.mmd -o output2.png -t dark
Generating single mermaid chart
```
You can find generated file: `output2.png` 


## Test WIth AsciidocFX

create `test1.adoc`


```
.Mermaid Diagram https://github.com/mermaid-js/mermaid-cli
[mermaid,target="mermaid-diagram"]
--
graph
   accTitle: My title here
   accDescr: My description here
   A-->B
--
```


![test-mmdc](https://github.com/asciidocfx/AsciidocFX/assets/101442875/5907b64f-73d4-4547-9158-3c48cfe71469)


[chapter-04.adoc.txt](https://github.com/asciidocfx/AsciidocFX/files/13403421/chapter-04.adoc.txt)

**Comment by savire** [comment]
![image](https://github.com/user-attachments/assets/5409a106-d40e-44a5-b9c0-d8e95cf2a0f3)
![image](https://github.com/user-attachments/assets/c1bf6ac4-9650-40de-b602-f4e6de85c6f8)
![image](https://github.com/user-attachments/assets/d52e92e5-8823-49bc-8ca5-4b96b420454c)

Weirdly enough the MathJax block example does not work right away on Windows 10 using the default download latest version. Its fresh install.

Also are we able to create our own custom extensions like with ascidoctor.js? If so is there any guide exist?

**Comment by life888888** [comment]
- Windows 11
- AsciidocFX 1.8.10 AsciidocFX_Windows.exe
 

```
-- *SAMPLE*

asciimath:[lim 2x^2]

.fomula 1
[latexmath,target="tex-formula-0"]
--
\begin{align}
  t & = texture_{color} [ uv_{color} ] \\
    
  color_{out}.xyz & = t.xyz \\
    
  color_{out}.w & = t.w * alpha
\end{align}
--

I change your code 

From 

```
[math,file="images/program.png",png]
```

To

```
[latexmath,target="tex-formula-0"]
```


```

![AsciidocFX_MathJAX](https://github.com/user-attachments/assets/d055c791-1f8f-4875-998b-34a7ec78a865)

**Comment by rahmanusta** [comment]
I'm not sure the syntax you used is correct. What do you see for the following example?

<img width="984" alt="image" src="https://github.com/user-attachments/assets/69ce2eb0-57b4-4bfb-b4e1-c1ae810c4842">

**Comment by rahmanusta** [comment]
That looks something is wrong in your example, you can verify the sample in matjax's own page https://www.mathjax.org/#demo

Getting starting to latex you can look at https://en.wikibooks.org/wiki/LaTeX/Mathematics

**Comment by savire** [comment]
> * Windows 11
> * AsciidocFX 1.8.10 AsciidocFX_Windows.exe
> 
> ```
> -- *SAMPLE*
> 
> asciimath:[lim 2x^2]
> 
> .fomula 1
> [latexmath,target="tex-formula-0"]
> --
> \begin{align}
>   t & = texture_{color} [ uv_{color} ] \\
>     
>   color_{out}.xyz & = t.xyz \\
>     
>   color_{out}.w & = t.w * alpha
> \end{align}
> --
> ```
> 
> I change your code
> 
> From
> 
> ```
> [math,file="images/program.png",png]
> ```
> 
> To
> 
> ```
> [latexmath,target="tex-formula-0"]
> ```
> 
> ![AsciidocFX_MathJAX](https://private-user-images.githubusercontent.com/101442875/372400980-d055c791-1f8f-4875-998b-34a7ec78a865.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTI4NTksIm5iZiI6MTcyNzg1MjU1OSwicGF0aCI6Ii8xMDE0NDI4NzUvMzcyNDAwOTgwLWQwNTVjNzkxLTFmOGYtNDg3NS05OThiLTM0YTdlYzc4YTg2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwNzAyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTAwY2JjNTExZjNmODBiZjkxM2JkZDU2MmExNzYyZDQ5YTVjOTg0YmNhYTdiZTI0OWZhNWExYmU0NjYxOTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9XywalKAw1Dtlw2NAxUjx8-V_7KtMsDkXJaVzZe4jZ4)



> That looks something is wrong in your example, you can verify the sample in matjax's own page https://www.mathjax.org/#demo
> 
> Getting starting to latex you can look at https://en.wikibooks.org/wiki/LaTeX/Mathematics

Hi @life888888 @rahmanusta 

Yes that solved the issue. Sorry I was just pasting random TeX code just to see it working or not.
Curious that the app it self gives below code as the default when we push the Mathjax (Block) Extension option.

```
[math,,png]
```

**Comment by numbworks** [comment]
Hello guys!

First and foremost thank you for your work so far! 

**Does somebody know how enable Mermaid support on Windows?**

At the moment, if I try to add a Mermaid diagram in AsciidocFX thru the [mermaid] block, I do get the following error:

> Failed to generate image: Could not find the 'mmdc' executable in PATH; add it to the PATH or specify its location using the 'mmdc' document attribute

The same .adoc file in Visual Studio Code with the AsciiDoc extension works just fine. 

Thank you for your help!

**Comment by rahmanusta** [comment]
You can find the details in readme https://github.com/asciidocfx/AsciidocFX

**Comment by numbworks** [comment]
@rahmanusta 
Thank you for your reply!

Just installing mermaid-cli doesn't work. :-(

I'll try to reinstall AsciidocFX from scratch. Let's see if it helps :-)

**Comment by life888888** [comment]
# Windows Config For Graphviz and mermaid-cli

## Install AsciidocFX

### Downdload AsciidocFX_Windows.exe

Brower open https://github.com/asciidocfx/AsciidocFX

Downdload AsciidocFX_Windows.exe

001

### Run Install
execute AsciidocFX_Windows.exe

## Install graphviz

### Downdload graphviz
Brower open https://graphviz.org/download/

Download windows_10_cmake_Release_graphviz-install-12.2.1-win64.exe

002

### Run Install
execute windows_10_cmake_Release_graphviz-install-12.2.1-win64.exe

Check the option `Add Graphviz to the system PATH for all users`

003

## Install NVM, NodeJS , NPM

Reference https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows

### Downlaod NVM
Reference https://github.com/coreybutler/nvm-windows#installation--upgrades

Browser open https://github.com/coreybutler/nvm-windows/releases

Select 1.2.2, Select assets: `nvm-setup.exe`

004

### Run Install
execute `nvm-setup.exe`

### Install NVM

open cmd.exe

```
mkdir C:\TEST123
cd C:\TEST123
nvm list available
```

get result:

```
|   CURRENT    |     LTS      |  OLD STABLE  | OLD UNSTABLE |
|--------------|--------------|--------------|--------------|
|   23.11.0    |   22.14.0    |   0.12.18    |   0.11.16    |
...
```

Select LTS version : `22.14.0`

in cmd.exe

```
nvm install 22.14.0
```

in cmd.exe

```
nvm use 22.14.0
```

### Install mermaid

```
npm install -g @mermaid-js/mermaid-cli
```

rsult:

```
added 419 packages in 2m
npm notice
npm notice New major version of npm available! 10.9.2 -> 11.3.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.3.0
npm notice To update run: npm install -g npm@11.3.0
npm notice
```

### UPDATE npm

```
npm install -g npm@11.3.0
```

## test mmdc version

In cmd.exe

```
mmdc --version
```

output:

```
11.4.2
```

## create test file

`input.mmd`

```
graph
   accTitle: My title here
   accDescr: My description here
   A-->B
```  

## Run test mmdc

In cmd.exe

```
mmdc -i input.mmd -o output2.png -t dark
```

result:

```
Generating single mermaid chart
[@zenuml/core] Store is a function and is not initiated in 1 second.
```
You can find generated file: `output2.png` 

## Test WIth AsciidocFX

create `test1.adoc`

```
.Mermaid Diagram https://github.com/mermaid-js/mermaid-cli
[mermaid,target="mermaid-diagram"]
--
graph
   accTitle: My title here
   accDescr: My description here
   A-->B
--
```

005 test1.adoc

AsciidocFX open Template Asciidoc-Book-Demo chapter-04.adoc

006 chapter-04.adoc


Update , add format example into chapter-04.adoc

```
.Mermaid Diagram https://github.com/mermaid-js/mermaid-cli
[mermaid, target="mermaid-diagram-1"]
--
graph
   accTitle: My title here
   accDescr: My description here
   A-->B
--

.Mermaid Diagram 2 https://github.com/mermaid-js/mermaid-cli
[mermaid, target="mermaid-diagram-2", format="png"]
--
graph
   accTitle: My title here
   accDescr: My description here
   A2-->B2
--


.Mermaid Diagram 3 https://github.com/mermaid-js/mermaid-cli
[mermaid, target="mermaid-diagram-3", format="svg"]
--
graph
   accTitle: My title here
   accDescr: My description here
   A3-->B3
--
```

007 

## list version

in cmd.exe
```
node -v

>>>> v22.14.0

npm -v

>>>> 11.3.0

mmdc --version

>>>> 11.4.2
```

**Comment by numbworks** [comment]
@rahmanusta 
Yes, reinstalling everything from scratch didn't help.

@life888888 
Thank you for your detailed instructions!

At the beginning, I installed only **NodeJS** (without **nvm** and **GraphViz**) and **mermaid-cli** wasn't generating any image at all.

Then I followed your instructions and **mermaid-cli** does generate the output image, but it stay stuck on:

`Generating single mermaid chart`

Despite the small progress, **AscidocFX** still doesn't display Mermaid diagrams on my **Windows 10** machine. 
It keeps showing the three black dots animation forever (and taking a whopping 1.5 GB of RAM). 

I think I'll use Visual Studio Code for exporting them, and show them as images in **AscidocFX**. 

@rahmanusta 
Maybe for a later version of **AscidocFX** it could be good to reduce dependencies (if possible) or integrate them as libraries or similar. 

In my humble opinion, this configuration procedure (nvm, nodejs, graphviz, ...) is overkill to follow for a basic Windows user and it limits the adoption of an otherwise good editor.

As comparison, the alternative solution takes two clicks (1. install VSCode; 2. install AsciiDoc extension) and everything works out of the box.

**Comment by life888888** [comment]
@rahmanusta 
VS Code's Asciidoc Extension is provided by Asciidoctor. Its description mentions that the rendering of various Diagrams is provided by asciidoctor-kroki. 

Since AsciidocFX has a reference to asciidoctor at the bottom, maybe AsciidocFX has a chance to reference asciidoctor-kroki? (https://github.com/asciidoctor/asciidoctor-kroki)

**Comment by rahmanusta** [comment]
Hi thanks @life888888   AsciidocFX uses asciidoctor-diagrams, not the kroki one.
