### ISSUE TITLE
Unable to launch in the last version

### ISSUE THREAD

**Issue by bobbyssubramaniam** [asciidocfx/AsciidocFX#626]
Debian Bookworm here, installed from the Deb package, this is the error:

```text
~ ❯❯❯ AsciidocFX
java.io.FileNotFoundException: log file directory '/opt/AsciidocFX/log' doesn't exist.
	at com.exe4j.runtime.LauncherEngine.checkRedirectionFile(LauncherEngine.java:196)
	at com.exe4j.runtime.LauncherEngine.doRedirection(LauncherEngine.java:172)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:59)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:71)
	at install4j.com.kodedu.boot.AppStarter.main(Unknown Source)
java.lang.NoSuchMethodError: 'java.lang.ClassLoader ch.qos.logback.core.util.Loader.systemClassloaderIfNull(java.lang.ClassLoader)'
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:73)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:66)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:52)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:195)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:182)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:490)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:476)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:425)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:451)
	at com.kodedu.boot.AppStarter.<clinit>(AppStarter.java:65)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71)
	at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:159)
	at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:726)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:71)
	at install4j.com.kodedu.boot.AppStarter.main(Unknown Source)
```

I created manually the log dir of /opt that shows in the message, but this dont solved the issue

mentions:  @thanatermesis

**Comment by bobbyssubramaniam** [comment]
Version 1.8.4 also shows error but a different one, related to compiled versions of java...

```text
java.lang.UnsupportedClassVersionError: com/kodedu/boot/AppStarter has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 63.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:80)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:69)
	at install4j.com.kodedu.boot.AppStarter.main(Unknown Source)
```

**Comment by bobbyssubramaniam** [comment]
It runs from the .tgz but not installing it from the .deb package, so the deb package is not working

**Comment by rahmanusta** [comment]
Please try the new version https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.8.9

**Comment by Thanatermesis** [comment]
Verified, it works, @bobbyssubramaniam you can install the newer version 1.8.9 from the .deb file and delete your previous directory of asciidocfx files, you can close this report now
