### ISSUE TITLE
Stalls, AsciidocFX problem? 

### ISSUE THREAD

**Issue by newbie-02** [asciidocfx/AsciidocFX#639]
[ edit ] for this moment I can think that this special occurence was 
triggered by another Java program running in background, 'tabula', 
closing for the moment [ /edit ] 
 
can't say for sure if this is an issue of AsciidocFX. 
 
experienced some stalls lately, mostly when having ~20 terminal windows, 
a browser with ~80 tabs and AsciidocFX with 4++ documants open from which 
one or more exceed 400k. 
 
Mostly need a reset, today could catch one by early closing the AsciidocFX 
window where the preview stalled, and looking in the terminal it was 
started from. 
 
Afaik the system wasn't short in CPU power or mem ( XFCE performance 
monitors waving between ~40 and ~80 percent usage while starting AsciidocFX 
easily get to 100 for some seconds ), read and write may be a bit slow reg. 
encrypted USB sticks. 
 
Can anybody drive any clue from the logs below? 
 
Or give advice how to triage / track down? 

catched stall: 
 
61858173 [] INFO  c.k.e.AsciidocAsciidoctorjConverter - Converted Asciidoc to HTML5 
61860725 [] INFO  c.k.e.AsciidocAsciidoctorjConverter - Converted Asciidoc to HTML5 
61860735 [] INFO  c.k.e.AsciidocAsciidoctorjConverter - Converted Asciidoc to HTML5 
61873834 [] INFO  c.k.e.AsciidocAsciidoctorjConverter - Converted Asciidoc to HTML5 
67405553 [] INFO  com.kodedu.service.PathMapper - Indexing.. /home/kali/transfer_stick 
67405583 [JavaFX Application Thread] INFO  c.k.service.ui.FileBrowseService - File browser relisted for /home/kali/transfer_stick 
67406722 [] INFO  c.k.e.AsciidocAsciidoctorjConverter - Converted Asciidoc to HTML5 
67420625 [] WARN  asciidoctor - 01_ieee_problems.adoc: line 4515: id assigned to section already in use: p_2_7 
[67428.180s][warning][gc,alloc] ForkJoinPool-1-worker-196: Retried waiting for GCLocker too often allocating 1420217 words
java.lang.OutOfMemoryError: Java heap space
67423966 [] WARN  asciidoctor - 01_ieee_problems.adoc: line 4515: id assigned to section already in use: p_2_7 
[67436.675s][warning][gc,alloc] ForkJoinPool-1-worker-199: Retried waiting for GCLocker too often allocating 3155885 words
java.lang.OutOfMemoryError: Java heap space
67439336 [] INFO  com.kodedu.service.PathMapper - Indexing completed.. /home/kali/transfer_stick 
67618293 [] INFO  c.k.e.AsciidocAsciidoctorjConverter - Converted Asciidoc to HTML5 
67619095 [] WARN  asciidoctor - 01_ieee_problems.adoc: line 4515: id assigned to section already in use: p_2_7 
67621725 [JavaFX Application Thread] WARN  javafx.css - Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.table-row-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621727 [JavaFX Application Thread] WARN  javafx.css - Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in module javafx.graphics@21.0.1 of loader 'app')' while converting value for '-fx-background-color' from rule '*.table-row-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621728 [JavaFX Application Thread] WARN  javafx.css - Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in module javafx.graphics@21.0.1 of loader 'app')' while converting value for '-fx-border-color' from rule '*.table-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621728 [JavaFX Application Thread] WARN  javafx.css - Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.table-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621729 [JavaFX Application Thread] WARN  javafx.css - Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in module javafx.graphics@21.0.1 of loader 'app')' while converting value for '-fx-border-color' from rule '*.table-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621730 [JavaFX Application Thread] WARN  javafx.css - Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in module javafx.graphics@21.0.1 of loader 'app')' while converting value for '-fx-border-color' from rule '*.table-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621730 [JavaFX Application Thread] WARN  javafx.css - Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.table-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621733 [JavaFX Application Thread] WARN  javafx.css - Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in module javafx.graphics@21.0.1 of loader 'app')' while converting value for '-fx-border-color' from rule '*.table-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621734 [JavaFX Application Thread] WARN  javafx.css - Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.table-row-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621734 [JavaFX Application Thread] WARN  javafx.css - Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in module javafx.graphics@21.0.1 of loader 'app')' while converting value for '-fx-background-color' from rule '*.table-row-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621735 [JavaFX Application Thread] WARN  javafx.css - Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in module javafx.graphics@21.0.1 of loader 'app')' while converting value for '-fx-border-color' from rule '*.table-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621736 [JavaFX Application Thread] WARN  javafx.css - Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.table-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621736 [JavaFX Application Thread] WARN  javafx.css - Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in module javafx.graphics@21.0.1 of loader 'app')' while converting value for '-fx-border-color' from rule '*.table-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621737 [JavaFX Application Thread] WARN  javafx.css - Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in module javafx.graphics@21.0.1 of loader 'app')' while converting value for '-fx-border-color' from rule '*.table-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
67621738 [JavaFX Application Thread] WARN  javafx.css - Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.table-cell' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/modena/modena.bss 
 
--------------------------------------------------------------------

try recreating the situation: 
 
347121 [] INFO  asciidoctor - possible invalid reference: Bild_08 
347122 [] INFO  asciidoctor - possible invalid reference: Bild_09 
347122 [] INFO  asciidoctor - possible invalid reference: Bild_10 
348234 [] INFO  c.k.e.AsciidocAsciidoctorjConverter - Converted Asciidoc to HTML5 
367404 [] WARN  asciidoctor - 01_ieee_problems.adoc: line 4515: id assigned to section already in use: p_2_7 
370218 [] ERROR com.kodedu.helper.IOHelper - Problem occured while reading file /home/kali/transfer_stick/content/content/disclaimer.adoc 
java.nio.file.NoSuchFileException: /home/kali/transfer_stick/content/content/disclaimer.adoc
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3268)
        at com.kodedu.helper.IOHelper.readFile(IOHelper.java:89)
        at com.kodedu.service.extension.processor.XrefIncludeProcessor.process(XrefIncludeProcessor.java:63)
        at org.asciidoctor.jruby.extension.processorproxies.IncludeProcessorProxy.process(IncludeProcessorProxy.java:109)
        at org.asciidoctor.jruby.extension.processorproxies.IncludeProcessorProxy$INVOKER$i$1$0$process.call(IncludeProcessorProxy$INVOKER$i$1$0$process.gen)

--------------------------------------------------------------------

ths file 'disclaimer.adoc' is included in the file I try to open, 
 
where: this document reproducibly stalls / is very slow, 
 
while another one even bigger in size and also including 'disclaimer.adoc' 
opens in seconds. 
 
Further tries with  closing the file(s) without closing AsciidocFX produced 
a situation where the 'bad' file didn't even open in the editor window, 
while the AsciidocFX stayed somewhat responsive and the other files could 
be closed, but the 'bad' files tab was resistive to closing. 
 

871784 [] INFO  c.k.e.AsciidocAsciidoctorjConverter - Converted Asciidoc to HTML5 
java.lang.RuntimeException: netscape.javascript.JSException: ReferenceError: Can't find variable: refreshUI
        at com.kodedu.service.impl.ThreadServiceImpl.lambda$runActionLater$2(ThreadServiceImpl.java:90)
        at javafx.graphics@21.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at javafx.graphics@21.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at javafx.graphics@21.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at javafx.graphics@21.0.1/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics@21.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: netscape.javascript.JSException: ReferenceError: Can't find variable: refreshUI
        at javafx.web@21.0.1/com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:160)
        at javafx.web@21.0.1/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
        at javafx.web@21.0.1/com.sun.webkit.WebPage.executeScript(WebPage.java:1576)
        at javafx.web@21.0.1/javafx.scene.web.WebEngine.executeScript(WebEngine.java:985)
        at com.kodedu.component.HtmlPane.lambda$refreshUI$1(HtmlPane.java:59)
        at com.kodedu.service.impl.ThreadServiceImpl.lambda$runActionLater$2(ThreadServiceImpl.java:86)
        ... 7 more

873670 [] INFO  asciidoctor - possible invalid reference: ste01 
873710 [] INFO  asciidoctor - possible invalid reference: ste01 
873715 [] INFO  c.k.e.AsciidocAsciidoctorjConverter - Converted Asciidoc to HTML5 
java.lang.RuntimeException: netscape.javascript.JSException: ReferenceError: Can't find variable: refreshUI
        at com.kodedu.service.impl.ThreadServiceImpl.lambda$runActionLater$2(ThreadServiceImpl.java:90)
        at javafx.graphics@21.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at javafx.graphics@21.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at javafx.graphics@21.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at javafx.graphics@21.0.1/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics@21.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: netscape.javascript.JSException: ReferenceError: Can't find variable: refreshUI
        at javafx.web@21.0.1/com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:160)
        at javafx.web@21.0.1/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
        at javafx.web@21.0.1/com.sun.webkit.WebPage.executeScript(WebPage.java:1576)
        at javafx.web@21.0.1/javafx.scene.web.WebEngine.executeScript(WebEngine.java:985)
        at com.kodedu.component.HtmlPane.lambda$refreshUI$1(HtmlPane.java:59)
        at com.kodedu.service.impl.ThreadServiceImpl.lambda$runActionLater$2(ThreadServiceImpl.java:86)
        ... 7 more

876700 [] INFO  asciidoctor - possible invalid reference: wel00 
876702 [] INFO  asciidoctor - possible invalid reference: sam05 
876702 [] INFO  asciidoctor - possible invalid reference: sam05 
876703 [] INFO  asciidoctor - possible invalid reference: sam05 
876728 [] INFO  asciidoctor - possible invalid reference: wel00 
876730 [] INFO  asciidoctor - possible invalid reference: sam05 
876731 [] INFO  asciidoctor - possible invalid reference: sam05 
876731 [] INFO  asciidoctor - possible invalid reference: sam05 
876733 [] INFO  c.k.e.AsciidocAsciidoctorjConverter - Converted Asciidoc to HTML5 
java.lang.RuntimeException: netscape.javascript.JSException: ReferenceError: Can't find variable: refreshUI
        at com.kodedu.service.impl.ThreadServiceImpl.lambda$runActionLater$2(ThreadServiceImpl.java:90)
        at javafx.graphics@21.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at javafx.graphics@21.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at javafx.graphics@21.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at javafx.graphics@21.0.1/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics@21.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: netscape.javascript.JSException: ReferenceError: Can't find variable: refreshUI
        at javafx.web@21.0.1/com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:160)
        at javafx.web@21.0.1/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
        at javafx.web@21.0.1/com.sun.webkit.WebPage.executeScript(WebPage.java:1576)
        at javafx.web@21.0.1/javafx.scene.web.WebEngine.executeScript(WebEngine.java:985)
        at com.kodedu.component.HtmlPane.lambda$refreshUI$1(HtmlPane.java:59)
        at com.kodedu.service.impl.ThreadServiceImpl.lambda$runActionLater$2(ThreadServiceImpl.java:86)
        ... 7 more

878830 [] INFO  c.k.e.AsciidocAsciidoctorjConverter - Converted Asciidoc to HTML5 
java.lang.RuntimeException: netscape.javascript.JSException: ReferenceError: Can't find variable: refreshUI
        at com.kodedu.service.impl.ThreadServiceImpl.lambda$runActionLater$2(ThreadServiceImpl.java:90)
        at javafx.graphics@21.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at javafx.graphics@21.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at javafx.graphics@21.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at javafx.graphics@21.0.1/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics@21.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: netscape.javascript.JSException: ReferenceError: Can't find variable: refreshUI
        at javafx.web@21.0.1/com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:160)
        at javafx.web@21.0.1/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
        at javafx.web@21.0.1/com.sun.webkit.WebPage.executeScript(WebPage.java:1576)
        at javafx.web@21.0.1/javafx.scene.web.WebEngine.executeScript(WebEngine.java:985)
        at com.kodedu.component.HtmlPane.lambda$refreshUI$1(HtmlPane.java:59)
        at com.kodedu.service.impl.ThreadServiceImpl.lambda$runActionLater$2(ThreadServiceImpl.java:86)
        ... 7 more

netscape.javascript.JSException: ReferenceError: Can't find variable: editor
        at javafx.web@21.0.1/com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:160)
        at javafx.web@21.0.1/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
        at javafx.web@21.0.1/com.sun.webkit.WebPage.executeScript(WebPage.java:1576)
        at javafx.web@21.0.1/javafx.scene.web.WebEngine.executeScript(WebEngine.java:985)
        at com.kodedu.component.EditorPane.getEditorValue(EditorPane.java:341)
        at com.kodedu.component.MyTab.save(MyTab.java:241)
        at com.kodedu.service.impl.ThreadServiceImpl.runActionLater(ThreadServiceImpl.java:80)
        at com.kodedu.component.MyTab.saveDoc(MyTab.java:264)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at com.kodedu.controller.ApplicationController.saveAllTabs(ApplicationController.java:1340)
        at com.kodedu.controller.ApplicationController.lambda$initializeSaveOnBlur$99(ApplicationController.java:1360)
        at javafx.base@21.0.1/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:372)
        at javafx.base@21.0.1/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
        at javafx.base@21.0.1/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:78)
        at javafx.base@21.0.1/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
        at javafx.base@21.0.1/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
        at javafx.base@21.0.1/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
        at javafx.graphics@21.0.1/javafx.stage.Window.setFocused(Window.java:702)
        at javafx.graphics@21.0.1/javafx.stage.Window$1.setFocused(Window.java:160)
        at javafx.graphics@21.0.1/com.sun.javafx.stage.WindowHelper.setFocused(WindowHelper.java:112)
        at javafx.graphics@21.0.1/com.sun.javafx.stage.WindowPeerListener.changedFocused(WindowPeerListener.java:65)
        at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:126)
        at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:178)
        at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
        at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:176)
        at javafx.graphics@21.0.1/com.sun.glass.ui.Window.handleWindowEvent(Window.java:1259)
        at javafx.graphics@21.0.1/com.sun.glass.ui.Window.notifyFocus(Window.java:1238)
        at javafx.graphics@21.0.1/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics@21.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
        at java.base/java.lang.Thread.run(Thread.java:1583)

netscape.javascript.JSException: ReferenceError: Can't find variable: editor
        at javafx.web@21.0.1/com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:160)
        at javafx.web@21.0.1/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
        at javafx.web@21.0.1/com.sun.webkit.WebPage.executeScript(WebPage.java:1576)
        at javafx.web@21.0.1/javafx.scene.web.WebEngine.executeScript(WebEngine.java:985)
        at com.kodedu.component.EditorPane.getEditorValue(EditorPane.java:341)
        at com.kodedu.component.MyTab.save(MyTab.java:241)
        at com.kodedu.service.impl.ThreadServiceImpl.runActionLater(ThreadServiceImpl.java:80)
        at com.kodedu.component.MyTab.saveDoc(MyTab.java:264)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at com.kodedu.controller.ApplicationController.saveAllTabs(ApplicationController.java:1340)
        at com.kodedu.controller.ApplicationController.lambda$initializeSaveOnBlur$99(ApplicationController.java:1360)
        at javafx.base@21.0.1/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:372)
        at javafx.base@21.0.1/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
        at javafx.base@21.0.1/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:78)
        at javafx.base@21.0.1/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
        at javafx.base@21.0.1/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
        at javafx.base@21.0.1/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
        at javafx.graphics@21.0.1/javafx.stage.Window.setFocused(Window.java:702)
        at javafx.graphics@21.0.1/javafx.stage.Window$1.setFocused(Window.java:160)
        at javafx.graphics@21.0.1/com.sun.javafx.stage.WindowHelper.setFocused(WindowHelper.java:112)
        at javafx.graphics@21.0.1/com.sun.javafx.stage.WindowPeerListener.changedFocused(WindowPeerListener.java:65)
        at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:126)
        at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:178)
        at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
        at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:176)
        at javafx.graphics@21.0.1/com.sun.glass.ui.Window.handleWindowEvent(Window.java:1259)
        at javafx.graphics@21.0.1/com.sun.glass.ui.Window.notifyFocus(Window.java:1238)
        at javafx.graphics@21.0.1/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics@21.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by rahmanusta** [comment]
I wonder if you can share any ‘bad’ files with us which is causing the issue?

**Comment by newbie-02** [comment]
alas not, but for this moment I can think that this special occurence was 
triggered by another Java program running in background, 'tabula', 
will close and try to reopen if new observations.
