### ISSUE TITLE
Windows installer does not remove old files

### ISSUE THREAD

**Issue by ellipticview** [asciidocfx/AsciidocFX#71]
Downloaded the windows.exe, version 1.3.6
Invoking the .exe file from the start menu leads to a process starting and just sitting there. No screen visible, no CPU usage.
Invoked bin/asciidocfx.bat from the command prompt. This results in the following:
```
C:\Program Files\AsciidocFX\bin>asciidocfx.bat
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.ClassCastException: org.apache.tomcat.websocket.WsWebSocketContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:124)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:109)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:961)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:950)
        at com.kodcu.boot.AppStarter.startApp(AppStarter.java:47)
        at com.kodcu.boot.AppStarter.start(AppStarter.java:35)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$153(Unknown Source)
        at com.sun.javafx.application.LauncherImpl$$Lambda$51/29950902.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$166(Unknown Source)
        at com.sun.javafx.application.PlatformImpl$$Lambda$45/28230490.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source)
        at com.sun.javafx.application.PlatformImpl$$Lambda$47/5712435.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source)
        at com.sun.javafx.application.PlatformImpl$$Lambda$46/1115142.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source)
        at com.sun.glass.ui.win.WinApplication$$Lambda$37/7135120.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: org.apache.tomcat.websocket.WsWebSocketContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
        at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:62)
        at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:243)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:149)
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createDeploymentManager(UndertowEmbeddedServletContainerFactory.java:345)
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:201)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:148)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:121)
        ... 22 more
```

**Comment by ellipticview** [comment]
Start a command prompt as administrator, and then running the batch file does give a different result as far as logging is concerned. But still no editor starts.
```
C:\Program Files\AsciidocFX\bin>asciidocfx.bat
20:12:03,987 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
20:12:03,987 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
20:12:03,988 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/C:/Program%20Files/AsciidocFX/lib/AsciidocFX-1.2.jar!/logback.xml]
20:12:03,988 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
20:12:03,988 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/Program%20Files/AsciidocFX/lib/AsciidocFX-1.2.jar!/logback.xml]
20:12:03,988 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/Program%20Files/AsciidocFX/lib/AsciidocFX-1.3.6.jar!/logback.xml]
20:12:04,006 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@7efdd7 - URL [jar:file:/C:/Program%20Files/AsciidocFX/lib/AsciidocFX-1.2.jar!/logback.xml] is not of type file
20:12:04,054 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
20:12:04,080 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@b7e884 - Adding [jar:file:/C:/Program%20Files/AsciidocFX/lib/spring-boot-1.2.0.RELEASE.jar!/org/springframework/boot/logging/logback/base.xml] to configuration watch list.
20:12:04,080 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@7efdd7 - URL [jar:file:/C:/Program%20Files/AsciidocFX/lib/spring-boot-1.2.0.RELEASE.jar!/org/springframework/boot/logging/logback/base.xml] is not of type file
20:12:04,087 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@b7e884 - Adding [jar:file:/C:/Program%20Files/AsciidocFX/lib/spring-boot-1.2.0.RELEASE.jar!/org/springframework/boot/logging/logback/defaults.xml] to configuration watch list.
20:12:04,087 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@7efdd7 - URL [jar:file:/C:/Program%20Files/AsciidocFX/lib/spring-boot-1.2.0.RELEASE.jar!/org/springframework/boot/logging/logback/defaults.xml] is not of type file
20:12:04,093 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word clr with class [org.springframework.boot.logging.logback.ColorConverter]
20:12:04,093 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wex with class [org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter]
20:12:04,096 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.springframework.boot.logging.logback.LevelRemappingAppender]
20:12:04,098 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [DEBUG_LEVEL_REMAPPER]
20:12:04,120 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.catalina.startup.DigesterFactory] to ERROR
20:12:04,120 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.catalina.util.LifecycleBase] to ERROR
20:12:04,120 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.coyote.http11.Http11NioProtocol] to WARN
20:12:04,120 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.sshd.common.util.SecurityUtils] to WARN
20:12:04,120 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.tomcat.util.net.NioSelectorPool] to WARN
20:12:04,120 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.crsh.plugin] to WARN
20:12:04,120 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.crsh.ssh] to WARN
20:12:04,120 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.jetty.util.component.AbstractLifeCycle] to ERROR
20:12:04,120 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.hibernate.validator.internal.util.Version] to WARN
20:12:04,120 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.boot.actuate.autoconfigure.CrshAutoConfiguration] to WARN
20:12:04,120 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.springframework.boot.actuate.endpoint.jmx] to false
20:12:04,120 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [DEBUG_LEVEL_REMAPPER] to Logger[org.springframework.boot.actuate.endpoint.jmx]
20:12:04,121 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.thymeleaf] to false
20:12:04,121 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [DEBUG_LEVEL_REMAPPER] to Logger[org.thymeleaf]
20:12:04,121 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@b7e884 - Adding [jar:file:/C:/Program%20Files/AsciidocFX/lib/spring-boot-1.2.0.RELEASE.jar!/org/springframework/boot/logging/logback/console-appender.xml] to configuration watch list.
20:12:04,121 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@7efdd7 - URL [jar:file:/C:/Program%20Files/AsciidocFX/lib/spring-boot-1.2.0.RELEASE.jar!/org/springframework/boot/logging/logback/console-appender.xml] is not of type file
20:12:04,124 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
20:12:04,126 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
20:12:04,133 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
20:12:04,187 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@b7e884 - Adding [jar:file:/C:/Program%20Files/AsciidocFX/lib/spring-boot-1.2.0.RELEASE.jar!/org/springframework/boot/logging/logback/file-appender.xml] to configuration watch list.
20:12:04,187 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@7efdd7 - URL [jar:file:/C:/Program%20Files/AsciidocFX/lib/spring-boot-1.2.0.RELEASE.jar!/org/springframework/boot/logging/logback/file-appender.xml] is not of type file
20:12:04,189 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
20:12:04,192 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
20:12:04,196 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
20:12:04,206 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@1038d3f - No compression will be used
20:12:04,215 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: ../log/asciidocfx.log
20:12:04,215 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [../log/asciidocfx.log]
20:12:04,217 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
20:12:04,217 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
20:12:04,217 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
20:12:04,217 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework] to ERROR
20:12:04,217 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.fop] to ERROR
20:12:04,217 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.kodcu] to DEBUG
20:12:04,217 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
20:12:04,218 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1fa396 - Registering current configuration as safe fallback point

   #                 #   #      #                #####  #   #
  # #    ####   ###          ####   ###    ###   #       # #
 #   #  ###    #     #   #  #   #  #   #  #      ####     #
 #####    ###  #     #   #  #   #  #   #  #      #       # #
 #   #  ####    ###  #   #   ####   ###    ###   #      #   #
 ============================================================
 :: Asciidoc FX ::        (v1.3.6)

 Website: http://asciidocfx.com

2015-04-09 20:12:05.907  WARN   --- [lication Thread] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
2015-04-09 20:12:05.935 ERROR   --- [lication Thread] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.ClassCastException: org.apache.tomcat.websocket.WsWebSocketContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:124)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:109)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:961)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:950)
        at com.kodcu.boot.AppStarter.startApp(AppStarter.java:47)
        at com.kodcu.boot.AppStarter.start(AppStarter.java:35)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$153(Unknown Source)
        at com.sun.javafx.application.LauncherImpl$$Lambda$51/29950902.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$166(Unknown Source)
        at com.sun.javafx.application.PlatformImpl$$Lambda$45/28230490.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source)
        at com.sun.javafx.application.PlatformImpl$$Lambda$47/5712435.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source)
        at com.sun.javafx.application.PlatformImpl$$Lambda$46/1115142.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source)
        at com.sun.glass.ui.win.WinApplication$$Lambda$37/7135120.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: org.apache.tomcat.websocket.WsWebSocketContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
        at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:62)
        at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:243)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:149)
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createDeploymentManager(UndertowEmbeddedServletContainerFactory.java:345)
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:201)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:148)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:121)
        ... 22 common frames omitted

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.ClassCastException: org.apache.tomcat.websocket.WsWebSocketContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:124)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:109)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:961)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:950)
        at com.kodcu.boot.AppStarter.startApp(AppStarter.java:47)
        at com.kodcu.boot.AppStarter.start(AppStarter.java:35)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$153(Unknown Source)
        at com.sun.javafx.application.LauncherImpl$$Lambda$51/29950902.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$166(Unknown Source)
        at com.sun.javafx.application.PlatformImpl$$Lambda$45/28230490.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source)
        at com.sun.javafx.application.PlatformImpl$$Lambda$47/5712435.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source)
        at com.sun.javafx.application.PlatformImpl$$Lambda$46/1115142.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source)
        at com.sun.glass.ui.win.WinApplication$$Lambda$37/7135120.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: org.apache.tomcat.websocket.WsWebSocketContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
        at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:62)
        at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:243)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:149)
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createDeploymentManager(UndertowEmbeddedServletContainerFactory.java:345)
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:201)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:148)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:121)
        ... 22 more
		
```

**Comment by rahmanusta** [comment]
We are using undertow instead of embedded tomcat. 

When look at ClassCastException: org.apache.tomcat.websocket.WsWebSocketContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer,

There is a tomcat dependency in your classpath. It firstly loaded before undertow websocket dependency and it crashes. Can you check lib folder and clear CLASSPATH environment variable ?

**Comment by ellipticview** [comment]
I'm not sure what you mean.
```
C:\Program Files\AsciidocFX\bin>dir ..\lib\t*.*
 Volume in drive C is System
 Volume Serial Number is D877-AD53

 Directory of C:\Program Files\AsciidocFX\lib

26/12/2014  10:26         2,823,177 tomcat-embed-core-8.0.15.jar
26/12/2014  10:26            41,176 tomcat-embed-logging-juli-8.0.15.jar
26/12/2014  10:26           233,342 tomcat-embed-websocket-8.0.15.jar
```

So the installer put these tomcat files here. The classpath is set in asciidocfx.bat

**Comment by rahmanusta** [comment]
As you see above, that files year is 2014. AsciidocFX 1.3.6 released at 2015. Please delete AsciidocFX folder and make fresh install.

**Comment by rahmanusta** [comment]
Did it solved your problem?

**Comment by ellipticview** [comment]
Deleting the folder and reinstalling solved the problem.
Suggest to have the installer clean the directory before installing new files.

**Comment by rahmanusta** [comment]
Great! Installer cleans old installation,  but bundled exe is not
