### ISSUE TITLE
JavaScript execution terminated on Windows (Win7, 64bit)

### ISSUE THREAD

**Issue by jueadams** [asciidocfx/AsciidocFX#88]
Since my document has grown (about 800 pages) it is not longer possible to create any output type from AsciidocFX GUI (Version 1.3.6, JRE included) on a Windows platform. Sometimes it works but in most cases it fails. 

From the log file I found:

Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: JavaScript execution terminated.
	at com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(Unknown Source)
	at javafx.scene.web.WebEngine.executeScript(Unknown Source)
	at com.kodcu.service.convert.RenderService.execute(RenderService.java:55)
	at com.kodcu.service.convert.RenderService.lambda$null$190(RenderService.java:86)
	at com.kodcu.service.convert.RenderService$$Lambda$563/275476971.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$50/208971515.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$49/1368601305.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$145(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$$Lambda$38/596286502.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I don't think this is an issue of AsciidocFX rather than a problem related to run JavaFX applications on Windows; the same project/source is working perfectly with AsciidocFX on MacOS (Snow Leopard) and Linux (CentOS 6.3) using the same version (1.3.6).

Thanks a lot - any ideas are always welcome.

**Comment by rahmanusta** [comment]
Hello @jueadams .

Why didnt you try to seperate documents with include:..[] element? Is this document public ? If public i can try it in my system.

**Comment by jueadams** [comment]
Hello @rahmanusta,

thanks for your advice. The book is organized chapter-wise using includes with documents stored in folders and sub-folders. This book, _not_ written by me,  was taken as "stress test" to check what will happen for a larger project. 
The source is available at https://github.com/elastic/elasticsearch-definitive-guide (for private use/non-commercial)  but I'd to change some markups that caused AsciidocFX to fail (another story). Therefore it is *not* possible to use the source directly from GitHub but I can provide the changed sources as an archive (about 3M, not that big).

Thanks a lot.

**Comment by rahmanusta** [comment]
Yes please share with me changed sources. Thanks for opinions.

**Comment by jueadams** [comment]
I send you the project via email. Did you receive the data?

**Comment by rahmanusta** [comment]
Hello @jueadams. Yes I got your email. I'll inform you :)

**Comment by jueadams** [comment]
Thanks for your help.
It is not that urgent as all went fine on *nix.
